fossasia/susi_android

app/src/main/AndroidManifest.xml

Wake lock permission is unnecessary in current feature list.

fixes #42 : removed Wake Lock permission.

---

app/build.gradle
app/src/androidTest/java/org/fossasia/susi/ai/test/MainActivityTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/MainApplication.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SplashScreen.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/splash_screen.xml
app/src/main/res/menu/menu_main.xml
build.gradle

Added realm database support to store conversation messages.

Fixes #11: Added local database

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

If user were writing multiple line message then edittext was covering
the large portion of UI. Now it covers 4 lines max.

Fixed Issue #49 : Text covering a multiline

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Arrow keys will only be visible if search finds something.
Also, on closing the search view, the highlighted search item goes back to original state.

Fixes Issue #112: Arrow Keys Bug

---

app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_message.xml

UI Enhancements

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java

**Fixes issue**
fixes issue #181 and #183 
**Changes:**
Fixed hiding of login and signup buttons when keyboard opens in Login and SignUp screens. Added back button on SignUp screen.

fixes issue #181 and #183: UI enhancements

---

app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Fixes issue #222 
Changes: search query is highlighted in messages with map and link.

Fix #222 highlighting search result in map and link message

---

app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/PieChartViewHolder.java

Fixes issue #191
Changes: 
Copy and Delete Feature is now working on all types of messages + snackbar is displayed to notify deletion too.
Not Applicable.

Fixes #191: Copy and Delete feature in Link Messages is not working

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/values/styles.xml

Fixes issue #227: Cursor not visible in sendMessageLayout
Changes: Cursor Color and Highlight color was changed for EditText in order to make it visible. 

Fixes #227: Cursor not visible in SendMessageLayout.

---

app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/values/dimens.xml

Fixes issue #232: query field input formatting for short input lines
Changes: The minSize of Layout was updated to not waste extra space. Some additional unnecessary margins were removed.

Fixes #232: query field input formatting for short input lines

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Fixes issue #249 
Now no crash due to imageLoading if Activity is destroyed.

Fix #249 crash due to LinkPreviewLoading

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #277 
Changes:  
- Rename voicereply() to voiceReply() and change signature to include isMap.
- If the reply is a map, remove the URL from the spoken reply.
NA

Fixed #277: Deactivate speech outputs for map URLs

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Possibly related to issue #289 
Changes: 
- The app crashes if t.getLocalizedMessage() returns null. Hence, add a null check.
NA

Fix crash if throwable message is null

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue 220. 
Changes: before chat background crop box is squre. now crop box is rectangular.

Fixes #220 Added crop box 16:9 in chat wallpaper

---

app/src/main/java/org/fossasia/susi/ai/SnackbarBehavior.java

Fixes issue #343
Changes: added onDependentViewRemoved to move Chat layout back to bottom, removed unused imports
Fixed: Snackbar dismissed manually, Chat layout doesn't come back down to its original position.

Fixes #343 Snackbar dismiss Chat layout position issue

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java

Fixes issue #348 
Changes: Saved the states before the orientation for both Login and Signup forms and updated the UI thereafter. Used savedInstanceState method.

Fixes #348 Data loss on orientation

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #350 . App not using standard voice and language of phone for text to speech.
Changes: Added support to use standard TTS voice with addition of Language preference inside of settings which on being clicked redirects to android TTS settings.

Added support to use standard android Text to Speech

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml

Fixes issue #361
Changes:Now a max width is setup for the chat bubble and the ticks always appear on bottom right.

 Fixes  #361: Minor UI issue resolved .

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/values/strings.xml

Fixes issue [#401](https://github.com/fossasia/susi_android/issues/401)
Changes: Implemented double back press to exit. Now whenever someone presses the back button, a Toast message will appear to press the button again to exit.

Fixes #401: Implemented double back press to exit

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/values/strings.xml

Fixes issue [#405](https://github.com/fossasia/susi_android/issues/405)
Changes: Implemented number of messages copied and displays with a toast message
**When only one message is copied.**
**When multiple messages is copied**

Fixes #405: Implemented number of messages copied

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/ChangePasswordActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java
exec/apk-gen.sh

Apk size reduced by 60 percent
Fixes issue #435 
Changes: build.gradle was configured to generate multiple APKs for 'x86', 'armeabi-v7a', 'mips', 'arm64-v8a' and 'x86_64' architecture. This finally reduced APK size from earlier 8.7 MB to 3.8 MB average.

Multiple APKs

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/values/strings.xml

Fixes issue [#410](https://github.com/fossasia/susi_android/issues/410)
Changes: Now the delete dialog shows how much messages the user is deleting with a toast message of number of messages deleted.

Fixes #410: Implemented number of messages to be deleted

---

README.md
app/build.gradle
app/fabric.properties
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/MainApplication.java

Fixes issue #290 
After a request by the developer, we can provide them the API Key until the final release of the product as sharing the API Key publicly is dangerous. Someone could this API key and  produce an app which could  destroys our analytics and can gain access user credentials.

Fixes #290: Proposed and implemented bug and crash logs using Fabric Crashlytics

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #446 : Wallpaper can now be selected using Google photos
Changes: Previously, the wallpaper selection using Google photos gave an error message "Unable to load image". Now it can be selected using the Google photos app. What i have tried is writing to temp file and return temp image URI, if it has authority in content URI.
Screen shots for the change:

Fixes #446 Now photos can be selected using Google photos

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Fixes issue #513 
Changes: Interacting with touchscreen during login now does not throw the "internet connectivity problem" error

Fixes issue #513: Login Bug

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/ImportantMessages.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/drawable/ic_grade_white_24dp.xml
app/src/main/res/drawable/ic_star_white_24dp.xml
app/src/main/res/layout/activity_important_messages.xml
app/src/main/res/menu/menu_main.xml
app/src/main/res/menu/menu_selection_mode.xml
app/src/main/res/values/strings.xml

Fixes # 522 : mark messages as important
added resources
updates!
adapter added but an unrecognized bug
finalized!
ready for pr
Fixes issue #522 
Changes: 
added a star button to mark message(s) important. provided a card in overflow menu to view important messages. on selecting important messages from the overflow menu, new activity opens up, giving out the messages marked as important. 
@the-dagger @jig08 please review! :)

Fixes # 522 : mark messages as important

---

app/src/androidTest/java/org/fossasia/susi/ai/TestLoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout/activity_login.xml

Fixes issue #496 
Changes:
- Added autoCompleteTextview in email for `LoginActivity`.
- Changed `TextInputEditText` to `AutoCompleteTextView` in `TestLoginActivity`.

fixes #496, added autoCompleteTextview in email for easy signup

---

README.md
docs/commitStyle.md

Fixes issue #638 
Changes: 
* Added commit style guidelines.
* Screenshots were looking small, changed the structure.

docs: Changed commit guidelines and screenshot structure

---

app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/layout/item_waiting_dots.xml
app/src/main/res/layout/search_item.xml
app/src/main/res/layout/search_list.xml

Fixes issue #673 
Changes: Adds margin at top of the message view. Now selected messages will appear in strips.
Screenshots for the change: **(UPDATED)**

Fix: Continuous selected chat bubbles strips

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #743 
Changes: initially answer text (I found this,here is the websearch result etc) was added with websearch,rss, map action type also. So on searching text like 'here', 'this' etc. text found in websearch, rss,map etc but since text is not shown in textview so app not show highlighted text. I changed the code to add answer in anchor and action type only.

Fix : search action  is not working properly

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #768 
ItemDecorator is added on onCreateViewHolder instead of onbindViewHolder as it is being called everytime when the recycleview is updated.

Fix : Removed error with itemDecorator on RecycleView.

---

app/src/main/res/drawable/rounded_button.xml
app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_forgot_password.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml

Fixes issue #784
Changes: Made the Button corners rounded in both Landscape and Portrait mode of Sign Up,Forgot Password, and Login Activity
Also Left aligned the radio buttons in forgot password and sign up Activity

Fix : Made the button corners rounded and aligned radio Buttons

---

app/src/androidTest/java/org/fossasia/susi/ai/ForgetPassTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/SignUpTest.kt

Fixes issue #858
Have written unit test for SignUp/Forget Pass using Expresso testing framework.

Espresso test for SignUp and ForgetPassword Activities

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt

Fix: Show correct title in settings fragment

---

app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt
app/src/main/res/values/strings.xml

Fixes #914 
Changed message in dialog in forgot password activity from "logging in" to "Resetting Password"

fix: change dialog message in forgot password

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/contract/IChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillData.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/SkillExamplesAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/viewholders/SkillExampleViewHolder.java
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillViewHolder.java
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingView.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/fragment_skill_listing.xml
app/src/main/res/layout/item_example_skill.xml
app/src/main/res/menu/skills_activity_menu.xml
app/src/main/res/values/strings.xml

Fixes #902 
Implement skill details section when a skill is clicked. example 
Google assistant
.
.
Skill cms
.
.
Added a "Try it" button so that user can just try the skill on the chat interface.

feat: Skill details fragment added

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt

Fixes #421 
onComputeMethod() cannot be called directly from computThread class if waiting for response instead other messages will be send to server after onSuccess or onFailure of previous response.
@chiragw15 please review if this works.

Fixes #421: getSusiMessage is called sequentially by queries

---

app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt

This PR is in reference to [#613](https://github.com/fossasia/susi_android/issues/613). 
Changes: 
Earlier client builder was being built at every instance of skill listing call. Now, Client Builder is being initialized only once and the same object is used in each skill call. This has reduced the skill loading time to half.

fix: Skills loading speed increased

---

exec/apk-gen.sh

Fixes #982
Changes:
- Rename upload file to `susi-release-signed.apk`

fix: Rename upload apk to correct file

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

Hide empty skillgroups
Fixes #968 
Changes: Hid the skill-group title and recyclerview if the group had no skills under it.

fix: Don't display empty skillgroups

---

app/src/main/res/layout/fragment_about_us.xml

Fixes #966
Changes: Added Ripple effect in all card views in about fragment

Added Ripple Effect in About Fragment

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #989 
Changes: Fixed TextToSpeech not stopping when app goes to background.

Fixed TTS not stopping when app goes to background

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

Fixes #981 
Changes: 
Made Picasso load up the placeholder image in case of error.
This is how it looked after this change, before [this](https://github.com/fossasia/susi_skill_data/pull/303) got pulled in. The placeholder images get loaded for the broken links.
Now we have the actual images:

fix: Display placeholder img for broken skill images

---

exec/apk-gen.sh

Fixes #999
Changes: 
- Force copy apk while generation
- Overwrite output file while ziplaligning
Reference : https://developer.android.com/studio/command-line/zipalign.html

chore: Force copy and align  apks while signing

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

Fixes #995 
Changes: 
AboutUsFragment and ChatSettingsFragment both inherited from android.support.v4.app.Fragment, whereas SkillDetailsFragment and SkillListingFragment use android.app.Fragment. This was causing problems with the fragment manager stack. So, for uniformity, changed everything to use the compatibility library.
Now, on pressing back, everything goes back to the skill listing fragment.

fix: Backbutton press in SkillsActivity

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #1003 
Changes: 
The crash was due to the lateinit variable being uninitialized during the textToSpeech.stop() call. To prevent crashing in other places where this might be happen later, I made it nullable. The only other way to fix this that I can see is by handling the exception that occurred instead (which doesn't prevent future crashes due to the same problem).

fix: App crash due to unintitialized textToSpeech

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java

* Crashing of app on input of a webpage
Fixes #961

Fixed Issue:

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

This PR is reference to #613.
Changes: Use builtin joinToString method instead of concatenating strings in loop at https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt#L130

fix: Do not concatenate strings in loop

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1028
Changes: 
Added a share button to SkillDetailsFragment to share a URI to the skill.

feat: Add share button to SkillDetailsFragment

---

circle.yml

Fixes #655 
Changes: Add Lint and Tests reports to CircleCI Artifact to be able to check them after the build process

Collect lint and tests reports

---

app/build.gradle
app/config.gradle
build.gradle
circle.yml
gradle/wrapper/gradle-wrapper.properties

Fixes #1071 
Changes: 
Replacements:
`compile` -> `implementation`
`debugCompile` -> `debugImplementation`
`testCompile` -> `testImplementation`
`androidTestCompile` -> `androidTestImplementation`
`releaseCompile` -> `releaseImplementation`
To obtain the above updates:
- Upgraded Android Gradle Plugin to `v3.0.1`
- Upgraded Gradle to `v4.1`
- Updated `circle.yml` file to support `buildToolsVersion = "26.0.2"`

Fixes #1071: Update dependency configurations

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/res/layout/activity_chat.xml

Fixes #1085 
Changes: Auto capitalisation has been enabled for the first letter of a sentence

Fix #1085 enable auto capitalisation of the first letter of a sentence

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Earlier the colors for positive and negative ratings were interchanged
in actual device though the android studio preview displayed them
correctly. This happened because of the interchanged strings labels
"Positive" and "Negative" in getRatedColor function in SkillDetailsFragment.kt
Fixes #1117 
Before :
After :
On actual device : 
Device used : Xiaomi Redmi Note 4

Corrected the colors associated with positive and negative ratings (Fixed #1117)

---

app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt

Fixes #1145 
Changes: Search icon no longer visible in the About Us Fragment.

Fix #1145-Search option hidden in the About us Fragment.

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt

Fixes #1149   -Added confirmation before exit on Login Screen
**Changes:**
1.Updated LoginActivity.kt overriding the back button pressed function and added 
confirmation  before exit when user is (logging in) in the app.
2. Added Toast that confirm the exit status at the login activity.
**Previously**
**After Updates**
**Note**
Toast will display "press again to exit". The gif displayed is not updated accordingly but the issue is fixed.You can see the updates in the code below.

Fixes #1149 -Added confirmation before exit on the login screen

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #1164 
Currently, the state of the list is not conserved when the device configuration changes from portrait to landscape. It was due to the logic in `OnLayoutChangeListener`. This pull request solves the issue by taking into consideration the configuration change of the device.

Retain scroll position of chat feed on configuration change

---

app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt

Fixes #1242 
Changes : Now the About Us Fragment does not contain a menu.

Removed menu from About Us Fragment (Fixed #1242)

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/values/strings.xml

Fixes #1193 
Changes: Use `Intent.createChooser()` instead of directly launching share
Screenshots of the change:

Fix #1193 - Let the user select his sharing medium

---

app/src/main/res/drawable/rounded_button_skilldetails.xml
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/item_skill.xml
app/src/main/res/layout/item_skill_group.xml
app/src/main/res/values/dimens.xml

Fixes #1196 
**Changes**
Implemented Material UI criteria in the Skill details and Skill listing. Also changed the UI a bit following the UI of Google assistant. The UI changes are as follows:
1. Making the Share and Try button in a rounded form with a different layout altogether in the skill details page and also changing the font size according to the Material UI guidelines. 
2. Also changing the format in which a skill in a block in the skill listing page, which even includes rearranging the heading of the skill. 
**Screenshots of the change**

Fix #1196: Changes the UI of Skill Listing, Skill details activity

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingPresenter.kt

Fixes #1227 
Changes: added a check before fetchGroups() in skillListingPresenter that we are loading skill data on activity creation or for Refresh

"double circularProgressBarFix"

---

app/src/main/java/org/fossasia/susi/ai/helper/AlertboxHelper.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/values/strings.xml

Fixes #1129
Changes: The reset password dialog is dismissed on tapping on the screen or on pressing the back navigation button, the AlertboxHelper class is now used for displaying the alert dialog to cancel the sign up process.

Fix #1129-Dialog issue resolved.

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout/activity_device.xml
app/src/main/res/layout/activity_welcome.xml
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/fragment_sttframe.xml
app/src/main/res/layout/item_example_skill.xml
app/src/main/res/layout/item_skill.xml
app/src/main/res/layout/item_susi_image.xml
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_image.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/layout/item_waiting_dots.xml
app/src/main/res/layout/rss_item.xml
app/src/main/res/layout/search_item.xml
app/src/main/res/layout/search_list.xml
app/src/main/res/menu/skills_activity_menu.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes #1312 
Changes: 
- Removed unused namespace declarations
- Use of 'sp' in place of 'dp' for text sizes
- Use of 'paddingEnd' along with 'paddingRight' etc. to better support right-to-left locale
- Used padding/Margin symmetry wherever possible
- Use of string resource for hardcoded strings

Fix lint XML warnings (Fixed #1312)

---

app/src/androidTest/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/login/WelcomeActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/signup/SignUpActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/skills/SkillsActivityTest.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/UtilModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/helper/ConstraintsHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/MediaUtil.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillGroupAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

Fixes #1315 
Changes: Removed redundant code constructs :
- Explicitly given type which is redundant
- Redundant overrides
- Redundant semicolons
- Unnecessary local variables
- Unused imports

Removed redundant constructs (Fixed #1315)

---

README.md

Fixes #1336 
Changes: Added the following libraries to README.md :
- MPAndroidChart : Used to plot charts.
- Timber : For logging.

Add missing libraries to README.md (Fixed #1336)

---

app/src/main/res/values/strings.xml

Fixes #1345 
Changes: All the strings in settings activity follow the same naming style. (First letter of first word will be uppercase while all others will be lowercase)

Use same styles to name strings in Settings Activity (Fixed #1345)

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Stars.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/strings.xml

Fixes #1355 
Changes: Now placeholder data has been replaced by live data from the getSkillList API to display the correct skill rating.

Fetch data from getSkillList API to display real time five star skill ratings (Fixed #1355)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/strings.xml

Fixes #1362 
Changes: Hid the rating bar when the user is not logged in.
**Screenshot : When user is logged in**
**Screenshot : When user is not logged in**

Hide rating bar when the user is not logged in (Fixed #1362)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1398 
Changes: Hide the skill rating text when rating bar shows zero rating.
Earlier : 
Now :

Hide skill rating text when the rating bar has zero rating (Fixed #1398)

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IChatModel.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
build.gradle

Fixes #1406 
Send device type in chat.json API 
Changes: 
Modified getSusiMessage() and getTableSusiMessage() functions to send device_type="Android" in the query 
NA

Send device_type=Android in the chat.json query

---

app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/res/values/array.xml

Fixes #1142 
Changes: Now the skills are shown in the skill listing activity in the language chosen by the user.
**Example : When the user chooses Hindi from Settings**

Show skills in the language chosen by the user (Fixed #1142)

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt

Fixes #1474 
Changes: Audio and video actions are fetched after the chathistory is retrieved

fix: Display audio and video action on history fetch

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #1478
Changes: Setting the default to en for all users, if the language is not present in the list preference.
@batbrain7 @arundhati24 Check now!

Language Crash Fix

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1454 
Changes: Now the toast pops up only when the user rates a skill and not each time the rating of the rating bar is updated.

Show toast only when the user rates a skill (Fixed #1454)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt

Fixes #1514 
Changes: Removed ellipsis at the end of the feedback text in the skill details screen.
**Screenshots for the change**
**Before**
**After**

Remove ellipsis at the end from the feedback text view (Fixed #1514)

---

app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/SkillMetricsDataQuery.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/SkillsBasedOnMetrics.kt
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillMetricsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillMetricsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingView.kt
app/src/main/res/layout/fragment_skill_listing.xml
app/src/main/res/values/strings.xml

Fixes #1517 
Changes: Now, the skills are shown in the skills activity based on various metrics like feedback, usage, rating and latest. This reduces the number of API calls (which was equal to the number of groups 
\+ 1 earlier) to just one API call i.e. from the getSkillMetricsData.json.
**Screenshot for current UI**

Show skills based on metrics in the skills listing fragment

---

app/src/main/java/org/fossasia/susi/ai/data/GroupWiseSkillsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IGroupWiseSkillsModel.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/GroupWiseSkills.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillFragmentCallback.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/viewholders/SkillViewHolder.java
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/contract/IGroupWiseSkillsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/contract/IGroupWiseSkillsView.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillMetricsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillGroupViewHolder.java
app/src/main/res/layout/fragment_group_wise_skill_listing.xml
app/src/main/res/layout/item_group_wise_skill.xml
app/src/main/res/values/strings.xml

Fixes #1539  [Parent issue #1467]
Changes: The skills belonging to a particular group are loaded in a new fragment when the user taps that group.

Show skills according to the group chosen by the user (Fixed #1539)

---

app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt

Fixes #1485 
Changes: Now the skills are loaded even when the user logs in for the first time.

Fixed problem loading skills when the user has not set a language explicitly (Fixed #1485)

---

app/src/main/res/layout/activity_chat.xml

Fixes #1578 
Changes: Swipe to type on the keyboard is now possible.

fix: Swipe to type on the chat activity keyboard

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/viewholders/SkillViewHolder.java

Fixes #1549 [Parent issue #1467]
Changes: Skill details shown when a skill card is clicked.

Load skill details when a skill card in GroupWiseSkillsFragment is clicked (Fixed #1549)

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1567 
Changes: The title bar now shows the correct titles for the Skills Listing Fragment, Group Wise Skills Listing Fragment and Skill Details Fragment.
**Screenshots**

Use appropriate action bar titles (Fixed #1567)

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/res/values/strings.xml

Fixes #1587 
Changes: Now, newest and top gaming skills are displayed in the skills listing page.

Add newest and top gaming skills to skills listing page (Fixed #1587)

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt

Use circular image view for skill image in group wise skill cards (Fixed #1633)

---

app/src/main/res/menu/skills_activity_menu.xml

Fixes #1644 
Changes: Now About option is shown at the bottom of the menu.

Move About option at the bottom in the menu (Fixed #1644)

---

app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt

Display skills images on skills card in a circular image view (Fixed #1655)

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/res/values/strings.xml

Add horizontal recyclerview to display staff picks on skills listing page (Fixed #1653)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1564 : Made examples sections invisible when example list is empty
Changes: Set the visibility to gone
Edit:
Screenshots:
@arundhati24 @batbrain7 Check this!

fix: make examples sections invisible when example list is empty

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml

Fixes #1686 
Changes: Removed translations for strings for which translatable attribute has been set to false, from other string localization files.

chore: Remove translations for strings with translatable attribute set to false

---

app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt

Fixes #1680
Changes: The email of all the users was anonymized in the feedback section. Now, the
email of the logged in user will not be anonymized.
**BEFORE**
**AFTER**

fix: Display the entire email string for the logged in user

---

app/src/main/res/values/colors.xml

Fixes #1719 
Changes: Changed the color primary of the app to #4285f4 .

fix: Use correct color primary to make it consistent with other clients

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt

Fixes #1806 
Changes: Removed leading and trailing whitespaces in input text

fix: Remove leading and trailing whitespaces in input text

---

app/src/main/AndroidManifest.xml

Fixes #1815
Changes: Added intent-filter in `WelcomeActivity` for google app-indexing. 
Open will open now when-
1. User tries to open a url: https://chat.susi.ai/app
2. Or programmatically via `susi.ai://` 

fix: GoogleAppIndexingWarning in AndroidManifest.xml (#1815)

---

app/src/main/res/values/strings.xml

Fixes #1821 
Changes: 
Changed the value of "url_susi_skill_cms" in strings.xml file from "http://www.skills.susi.ai" to "https://skills.susi.ai"

fix: Change the url of susi-skill in about-us

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes : #1819 
Changes: Changed default value of CUSTOM_SERVER from null to "", which is required since the default value must be empty (not null) when the app is used for the first time.

fix: App crash when trying to change server backend in settings

---

app/src/main/res/layout-land/fragment_skill_details.xml

Fixes #1876 
report skill setOnClickListener shows null value. Because there is no such resource in landscape layout file
Changes:
Added the reportSkill TextView in landscape layout resource

fix: Fixed app crash in skill when in landscape

---

app/src/main/res/layout/fragment_group_wise_skill_listing.xml

Fixes #1895 There should be a scroll bar in showGroupWiseSkill fragment
Changes: Added vertical scrollbar

fix: Add scroll bar in ShowGroupWiseSkill fragment

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

Fixes #1893 App crashes on scrolling down while in skills activity
Changes: 
Replaced .empty() function with null check for skillName as it was causing error on null string.

fix: Checking null along with empty 

---

app/src/main/res/xml/pref_settings.xml

Fixes #1700
Changes:
Disabled the selectable feature for "No Connected device"
And disabled selectable feature for "Login email" as there is no action required for these

fix: Fixed selectable in settings

---

app/src/main/res/layout/search_bar.xml

Fixes #1372 
Changes: 
I think this the issue is because the "Search Skill" is wrapped and when we tap just left of cross icon the keyboard doesn't appear.
The solution for this is just making it match with parent.
Made the search bar match parent from wrap content

fix: Made search bar match parent

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #1921 Contradicting options can be selected in settings 
Changes: 
Made one of the options false if other is made true by user

fix: One speech option selected at a time

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

Fixes #1992
Changes:
Whenever the cancel is called the fetching process is continuing. So, if we put it in the while loop till all the calls are cancelled then it'll be working fine.

fix: fixes crash

---

app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/values/strings.xml

Changes: On pressing back button at sign up activity, a dialog box appears for confirmation which is a bit confusing. You can see in the below image that both options can be thought as the option to exit the activity by different users. So I've updated the text so as to provide convinient options.
Before:
After:

chore: sign up activity cancel dialog box updated

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #2050 
Changes:chat settings fragment

fix: Title change to settings on moving back from about us

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt

Fixes #2069 s #IssueNumber]
Changes: Name of skill is shown now in GroupWise skills

fix: name of skill now showing in groupwise skills

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt
app/src/main/res/values/strings.xml

Fixes #2071 
Changes: Now placeholder values of example and author name of skill data is not showing

fix: Placeholder values of author name and example is not showing now in GroupWise Skills

---

app/src/main/AndroidManifest.xml

Fixes #2088 
Changes: 
Changed the typo from "Replay" to "Replace" in Manifest file

fix: fixes the typo in Manifest file

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pt-rBR/strings.xml

Fixes #2122 #1879 
Reasons for Crash: In ChatSettingsFragment, findPreference(key) method returns null to hotword detection which should not be the case. Null was returned due to invalid key passed when language is changed to Hindi.
Changes: I've removed the unwanted Hindi and other languages key to avoid the crash.

fix: settings crash after changing language

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/layout/fragment_sttframe.xml
app/src/main/res/layout/item_voice_commands.xml

Fixes #2150 
Changes:When the user talks, the txtchat is hidden by the voice commands.
Modified it by reducing the size and making it top of txtChat

fix: modified voice commands

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/privacy/PrivacyFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/menu/skills_activity_menu.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ml-rIN/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes #2152 
Changes: Transferred Privacy, Help, ABout option from the menu to the settings page.

fix: Moved help, privacy, about option from menu to settings

---

app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/res/values-hi/strings.xml
app/src/main/res/values/strings.xml

Fixes #1955 
Changes: 
* Corrected the present code of hyperlinking words in text view
* Updated the string format

fix: Hyperlinked words in textview instead of whole textview

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #2177 
Changes: [Add here what changes were made in this issue and if possible provide links.]

fix: Made search, susi icon invisible in stt fragment

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixes #2212
Changes: 
Upgarded the required files.
Fixed the gradle build.
Probably developers have to update to the latest version of the android studio, to prevent any errors from rising.

chore: bump gradle from 3.3.2 to 3.4.1

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt

Fixes #2136
Changes: 
Pressing back button in login page leads to the chat activity now. This was decided in the comments in an old pr.

fix: Back press in login activity handled

---

app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/res/drawable/ic_settings_voice_black_24dp.xml
app/src/main/res/menu/skills_activity_menu.xml
app/src/main/res/values/strings.xml

Fixes #2082 
Changes: 
Added voice search icon in action bar, clicking on which prompts voice search.

feat: Voice search implemented on skills listing

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsPresenter.kt
app/src/main/res/values/strings.xml

Fixes #2126 
Changes: 
If user is not logged in, and he wants to rate a skill. Clicking on rate skill redirects to login page

feat: Implement the feature to redirect to login page to rate skills

---

app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt

Fixes #1783 
Changes:
Added Hotword recognition call method even if the speech recognition fails
Screenshots for the change: No relevant change in UI
Apk:
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3270839/app-fdroid-debug.apk.zip)

fix: hotword detection problem after speech recongnition fails

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #2055 
Changes: [Add here what changes were made in this issue and if possible provide links.]
Fixed it by checking whether the user is logged in or not. Initially, it used only anonymity as a parameter to check

fix: Fixed malfunction of settings fragment

---

app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt

Fixes #1739 
Changes: 
Now the intent speech recognition runs through the default language of the system.

fix: Run speech recognition in default language

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt

Fixes #2252 #2249 
Changes:
Users can now connect to the smart speaker, even if his mobile is connected to a wifi network. Also, the app can connect to the smart speaker, if the app tried to connect to the device before (susi.ai hotspot password saved in cache).

fix: Fix smart speaker connectivity problem during different wifi connection of device

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MessageViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/YoutubeVideoViewHolder.kt

Fixes #2269 
Changes: Added the API call at only one place which is the MessageViewHolder which is extended by other viewholders

chore: refactor rateskill code in viewholders

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/data/contract/IRoomModel.kt
app/src/main/java/org/fossasia/susi/ai/data/device/RoomModel.kt
app/src/main/java/org/fossasia/susi/ai/data/model/RoomsAvailable.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/AddDeviceQuery.kt
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetAddDeviceResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt
app/src/main/res/drawable/ic_add_24dp.xml
app/src/main/res/drawable/ic_home_black_24dp.xml
app/src/main/res/layout/fragment_device_connect.xml
app/src/main/res/layout/room_layout.xml
app/src/main/res/layout/room_recycler_layout.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #2266 
Changes: 
Implemented the UI that would handle the addition of rooms
Screenshots for the change: WIll add it soon

feat: Add room feature

---

app/src/main/java/org/fossasia/susi/ai/skills/feedback/FeedbackActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt

Fixes #2023 #1453 
Changes: 
The feedback is now ordered in a way such that, if the user has feedback, then it gets displayed at the top and the rests are ordered by the newest first.
Apk: 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3282758/app-fdroid-debug.apk.zip)

feat: Order feedback by date

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/RoomsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
app/src/main/res/drawable/ic_delete_black_24dp.xml
app/src/main/res/layout/room_recycler_layout.xml
app/src/main/res/values/dimens.xml

Fixes #2287
Changes: 
User can now delete the name of the rooms he added before
Apk: 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3341963/app-fdroid-debug.apk.zip)

feat: Delete rooms in the device connect fragment

---

app/build.gradle
app/config.gradle
app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/login/contract/ILoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/login/contract/ILoginView.kt
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/values/strings.xml

Fixes #1301 
Changes:
Users can now save their login credentials using smart lock features (Credential API of google). Credentials are stored only if the user selects the remember me options. If clicked so, it auto fills the fields, next time when the user wants to log in.

feat: Implement remember me option in login screen

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/WifiViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
app/src/main/res/layout/fragment_device_connect.xml
app/src/main/res/layout/password_layout.xml
app/src/main/res/layout/wifi_password_layout.xml
app/src/main/res/values/strings.xml

Fixes #2306 
Changes:
Instead of the alert dialog box, now we have a layout to enter a password for the wifi. This is similar to the one present in Google Home.

feat: Show wifi password layout

---

app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt

Fixes #2314
Changes: 
* Just change the URL by using which we fetch the list of connected devices. Rest everything remains the same.

feat: Update url to show display of connected devices
