settings.gradle

@mariobehling the old module's name was still there. Corrected it.

Fixed module name

---

.idea/misc.xml
.travis.yml
app/build.gradle
app/src/androidTest/java/org/fossasia/susi/ai/test/ApplicationTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/ChatMessageAdapter.java
app/src/main/java/org/fossasia/susi/ai/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/SplashScreen.java

Push Travis notifications to loklak gitter channel

---

app/src/main/java/org/fossasia/susi/ai/MainActivity.java

UI is not getting blocked anymore on sending new message.
fixes #17.

moved Network call off UI thread.

---

app/src/main/java/org/fossasia/susi/ai/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

abstracted adding, notifying and scrolling inside recycler adapter.

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/ChatViewHolder.java
build.gradle

Added butterknife for faster development.
Fixes issue #25

Fixes #25 : Added butterknife

---

README.md
docs/Android_App_Setup.md

PR Fixes #2 by adding setup information to docs and readme.

Fixes #2: Added setup information

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/SplashScreen.java
app/src/main/res/layout/splash_screen.xml

Adressed #31 .
* Activity now extends AppcompatActivity
* Image is now loaded dynamically.
* Improved layout by decreasing one level.

fixes #31: multiple performance issues with splash screen.

---

app/src/main/java/org/fossasia/susi/ai/MainActivity.java

Fixes issue #15 to solve this issue added some code in mainactivity to hide soft keyboard so that it will open only when user touch edittext.

Fixes issue #15: solved soft keyboard get open automatically 

---

app/src/main/java/org/fossasia/susi/ai/MainActivity.java

Removed the OnClick functionality from the Avatar Icon. Not Required and nullable.

Fixes #34: Crash on Avatar OnClick

---

app/src/main/res/layout/item_mine_message.xml

How about give a link for url in message? Like when I input "check google.com", the link has been set to google.com. Please look on.

Make link for url in message

---

README.md

Fix #51 Change gitter badge

---

app/src/main/java/org/fossasia/susi/ai/MainActivity.java
app/src/main/res/layout/activity_main.xml

now trims white spaces and newline characters.
Removed Relative layout default padding as it was looking unusual with android default pull animation

Fixed : sending newline characters

---

README.md

The gitter channel link has been updated to  https://gitter.im/fossasia/susi_android in README.md

Updated Gitter Channel Link

---

app/src/androidTest/java/org/fossasia/susi/ai/test/MainActivityTest.java

It is a preTest for issue #39. Will add Unit test after this.

Added instrumentation test

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_mine_image.xml
app/src/main/res/layout/item_mine_message.xml
app/src/main/res/layout/item_other_image.xml
app/src/main/res/layout/item_other_message.xml
app/src/main/res/values/colors.xml

* Changed colors, same as web client.
* Optimised layouts.
fixes #62.
ScreenShot:

adressed #62: linkified all links sent by susi.

---

docs/Android_App_Setup.md

Corrected Android_App_Setup.md

Corrected Android_App_Setup.md

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

fixes issue #75 Now whenever app will start it show last chat between user and AI.

fixes issue #75 Now whenever app will start it show last chat between user and AI.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

User can select between to choose whether to use Enter key to send
message or function as normal .

Issue 48 Fixed. Added Enter Key as Send Feature.

---

.travis.yml
exec/apk-gen.sh

@the-dagger Please add Github API key and then merge.
Also #1 can be closed. Please Update Webhook URL to post to susi_android gitter channel.

Update #3: Add apk on build success

---

app/src/main/java/io/realm/internal/network/NetworkStateReceiver.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Also did some realm related optimisations.

fixes #85 : fixed crash due to realm issue.

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/res/layout/activity_settings.xml
app/src/main/res/xml/pref_settings.xml

fixes #91 : updated  settings UI to material design.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/values/dimens.xml

> Note: clear application data before running

fixes #67: added chat timestamp

---

app/src/main/java/org/fossasia/susi/ai/MainApplication.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/helper/AndroidHelper.java
app/src/main/java/org/fossasia/susi/ai/helper/MapHelper.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/layout/item_susi_map.xml

Maps are now implemented in app.
clicks on map have 2 cases:
1. if google maps is installed open location in google maps
2. if app is not installed, fallback to OpenStreetMap link and open in browser.
Screenshot:

fixes #63 : Added support for maps.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
gradle.properties

improve UI while searching in messages

---

app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

fixes issue #108 Now if search text found then only text background colour will change.

fixes issue #108 improving search UI

---

app/src/main/res/layout/activity_main.xml

Added the one liner for verticle scroll bar to activity_main.xml layout's recycler view

Fixes #115 enabled scrollbar for chat

---

app/src/androidTest/java/org/fossasia/susi/ai/test/MainActivityTest.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/layout/activity_main.xml

Now the single button can work as send as well as speech to text input.

Fixes #113: UI improvement

---

app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

fixes issue #108 and #130 in my previous commit I changed only user-message and forgot to change susi-message background colour so solved that issue.Now if search text found then only text background colour will change.

fixes issue #108 and #130 improving search UI

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.java
app/src/main/res/values/strings.xml

fixes #141 Managed Hard Coded Strings in strings.xml.

Fixes #141: Managed Hard Coded Strings in strings.xml

---

app/src/main/java/org/fossasia/susi/ai/MainApplication.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.java

PrefManager Helper for Managing SharedPreferences.

Fixes #144: PrefManager Helper for Managing SharedPreferences 

---

app/build.gradle
app/src/androidTest/java/org/fossasia/susi/ai/TestMainActivity.java

1. check main container views on app launch
2. check action bar item  on app launch
writing other test cases..

Fixes #39 Added espresso test cases to check visibility of views

---

README.md

fixes #148 add codacy to the project

---

app/src/androidTest/java/org/fossasia/susi/ai/TestMainActivity.java
app/src/main/AndroidManifest.xml

fix 39 : fix failing connectedTests

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.java
app/src/main/java/org/fossasia/susi/ai/rest/BaseUrl.java
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/java/org/fossasia/susi/ai/rest/model/SusiBaseUrls.java

Made base url abstract, So we can change base url, when ever we want.
Added BaseUrl.java for managing Base Url. Like we will add a method to change base url in SharedPreferences and refresh the Retrofit Object by calling ClientBuilder.createSusiService()
and it's done, do not need to do anything else.

Fixes #155: Back-End Configuration and fail-over 

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

fixes issue #147 add an option in setting to disable STT

fixes issue #147 add an option in setting to disable STT

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_user_link_preview.xml
build.gradle

#70 Link Previews are added.
#157 Map Messages now have a time stamp.
Link Previews added with shortened URL also working.
targetSdk updated to 24 in build.gradle

Fixes #70 and #157: Added Website Link Previews

---

app/src/androidTest/java/org/fossasia/susi/ai/TestLoginActivity.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.java
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java
app/src/main/java/org/fossasia/susi/ai/rest/interceptors/TokenInterceptor.java
app/src/main/java/org/fossasia/susi/ai/rest/model/LoginResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/model/SignUpResponse.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

* Implemented Sign UP and Log in screens with functionality. UI still needs to be worked upon.
* Added a new test case to follow auth system.
this also partially addresses #169. we still need to decide an accent color.

fixes #132: implemented authentication system.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #175 now it is working properly

fixes issue #175 selecting mic as input not working properly

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/PieChartViewHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/rest/model/Answer.java
app/src/main/java/org/fossasia/susi/ai/rest/model/Datum.java
app/src/main/res/layout/item_susi_piechart.xml
build.gradle
gradle.properties

Fixes #95 and Fixes #107 added pie chart,feature to send messages afterconnecting to internet

---

app/src/main/res/drawable/rounded_layout_cyan.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/values/dimens.xml

1) Mid Width defined for message layouts
2) New TimeStamp Layout Applied to Map and LinkPreview views too.

Fixes #177 : UI Issues with Timestamps

---

.travis.yml
app/src/androidTest/java/org/fossasia/susi/ai/TestMainActivity.java
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml

Fixes #39, Merged with Login test and added 2 new test cases for MainActivity

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes #152 : Text to speech feature added.

---

app/src/debug/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SplashScreen.java
app/src/main/java/org/fossasia/susi/ai/rest/BaseUrl.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java
app/src/release/java/org/fossasia/susi/ai/rest/ClientBuilder.java

Added Logic to change base Url whenever SocketTimeoutException will come
Added method in BaseUrl to change base url.

fixes #156: Added the logic to change base url whenever SocketTimeoutException will come

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Fixes issue #208 
Changes: Alert Dialog was modified a bit

fixed #208 UX improvement

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java
app/src/main/res/drawable/rounded_layout_green.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/colors.xml

Fixes #197: Log in Sign up UI updated.

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Fixes issue #203
Changes: 
Added new realm adapter dependency and specified sorting order for messages explicitly.

fixes #203: message deletion now works properly.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

Fixes issue #206 
Changes:
Audio Focus added to text to speech.

Fixes #206 : Audio Focus issues resolved.

---

README.md
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/values/dimens.xml

Fixes issue #229: Design Inconsistency in Pie Chart Layout.
Changes: 
- Layout modified to match rest of layout designs.
- Readme.md updated to guide new contributors to follow uniform design language.
Before:
After:
PieChart Layout not yet operational so can not provide them.

Fixes #229: Design Inconsistency in Pie Chart Layout.

---

app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/ChatFeedRecyclerAdapter.java

On settings menu , when we press back button now , the app does not crashes instead goes to main activity.

Fixes #196 : Back button issue resolved

---

app/src/main/java/org/fossasia/susi/ai/SnackbarBehavior.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/layout/activity_main.xml

Fixes issue #160
Changes: Added Coordinator Layout Behavior listener to RelativeLayout and Linearlayout inside MainActivity layout

Fixes #160 : Snackbar layout lifting problem resolved

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #118
Changes: When device is not support editing then image select automatically set as a chat background.

Fixes #118 Bug: in new Wallpaper feature

---

app/src/main/res/layout/activity_login.xml
app/src/main/res/values/strings.xml

Fixes issue #240 
Changes: now the text field don't extend when Enter is pressed. Remove hardcoded strings from activity_login.xml and add them to the strings.xml file.

Fixes #240 Issue with Email field of login screen

---

app/src/debug/AndroidManifest.xml

Fixes issue #253 
Changes:
added 2 manifests with different permissions
compiled debug manifest:
release manifest:

fixes #253: setup separate manifests for debug and release.

---

app/src/main/res/layout/activity_main.xml

Fixes issue #248 
Changes: made date-view over recyclerView so there is no margin problem.

Fix #248 excessive top margin of chatbox + date-view over RecyclerView

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Fixes issue #246: Issue in password field of login screen
Changes: 
- Password Validation check removed for login screen. Now a login will be attempted even if password does not matches registration criterion.

Fixes #246: Issue in password field of login screen

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #143 search query and messaging mismatch

Fixes issue #143 search query and messaging mismatch

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/TypingDotsHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/ZeroHeightHolder.java
app/src/main/res/layout/item_waiting_dots.xml
app/src/main/res/layout/item_without_height.xml

Fixes issue #186 
Changes: WaitingDots feature added

Fixes #186 V2 WaitingDots feature added

---

app/src/main/java/org/fossasia/susi/ai/SnackbarBehavior.java

Fixes issue #270 
Changes:
- Fixed SnackbarBehavior
- It now properly animates the entire layout when a Snackbar is displayed.
https://gfycat.com/BlandScentedBasil

Fixes #270: Fixed SnackbarBehavior

---

app/src/main/java/org/fossasia/susi/ai/SnackbarBehavior.java
app/src/main/res/layout/activity_main.xml

Fixes issue #251 #275 
Changes: Overlapping corrected

Fixes #251 & #275 Overlapping of views corrected

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/styles.xml

Fixes issue #267 simplify design of login/signup screen

fixes issue #267 simplify design of login/signup screen

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #276
Changes:Now the speech output is given only when the user gives input via speech to text.
It can be disabled in the settings as well.

 Fixes #276 : Speech Output issue resolved.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
build.gradle

Fixes issue #284
Changes: Added Alert Dialog Box for Logout Screen

Fixes #284 added alert dialog for logout screen

---

app/src/main/res/layout/activity_main.xml

Fixes issue #304
Changes: Alignment of send button corrected

Fixes #304 Alignment of send button fixed

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java

Fixes part 1 of issue #185 
Changes: 
-trimmed email at isEmailValid check
-trimmed before calling Login
-trimmed before calling SignUp
Screenshots: None

Fixes issue 1 of #185 . trim email for signup and login

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Changes: [Add butterknife clicking to signup in Login screen. Remove TextView & click listener.]

Add butterknife to signup

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Fixes issue #319
Changes: Alert for invalid password added.

 Fixes #319 : Invalid password issue solved.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/values/strings.xml

Fixes issue #309 
Changes: Two errors were identified and shown accordingly:
1. Invalid Access Token
2. Internet Connectivity Problem

Fixes #309 Show relevant error messages

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #325
Changes: Delete confirmation added.

 Fixes #325 : Delete confirmation issue.

---

app/src/main/res/drawable/rounded_layout.xml
app/src/main/res/layout/activity_main.xml

Fixes issue #327 
Changes: Added border to edit text in home activity.

Adding border to edit text in home activity

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #318
**Changes**
Created a handler inside the onActivityResult method of the MainActivity.
**Earlier**
Susi used to crash when we asked susi about location as "Where is New Delhi."
**Now**
Susi doesn't crashes and gives positive results.
Thanks

Fixes #318 Added a Handler in the onActivityResult() method.

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #334 <Categorised the Settings Activity.>
**Changes**
Categorised the settings activity into :
1). Chat Settings
2). Mic Settings
3). Speech Settings
Screenshots for the change :

Issue #334<Categorised the Settings Activity.>

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #336. TTS now says "Conducting a Search.....Launching Browser." whenever it conducts a web Search.
Changes: Earlier the TTS used to speak "I don't know" whenever it had to launch a web search. But now the TTS says the desired message.
Thanks. :)

Fixes #336 TTS now says the desired message.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #331
Changes: Now when we copy the map messages the link will not get copied along with the message.

 Fixes  #331: Map message copy issue .

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #340
Changes: I have used the split function with whose help I have reconstructed the string. Now Susi for Multi Line query is working in the same way as it works for Single Line Query.

Issue #340 MultiLine query support added.

---

app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/strings.xml

Fixes issue #354
Changes: added scrollview as parent

issue #345 added scrollview as parent

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultsHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/rest/model/Datum.java
app/src/main/res/layout/search_item.xml
app/src/main/res/layout/search_list.xml

Fixes issue #150 .
Changes: added horizontal recycler view for search results. 

fixes #150: added support for search results.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/values/colors.xml

Fixes issue #362 
Changes: Color corrected of link and searched text.

Fixes issue #362: Color correction of link and searched text

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #364
Changes: Now if the user doesn't type any message and just print space the message will not be sent as send button will get deactivated if the message is null.

Fixes #364 : Empty messages issue resolved.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #364 
Changes: Solving empty message issue

Fixes issue #364: Solving empty message issue

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #365 
Changes: Clarified settings activity's titles.

Fixes issue #365: Clarified settings activity's titles

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/model/Action.java

Fixes #252: Add option to display multiple answer lines

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java

Fixes issue #371 
Changes: Added a timezoneOffset parameter in SusiService. Calculated the offset before calling the query in MainActivity.
Verified value of timezoneOffset before sending to server.
More info:
Calculation for time should be corrected at server side. Right now it exceeds 24 hours and rounds off timeOffset of 30 mins to 1 hour.

Fixes #371. Added timezoneOffset in susi api call

---

app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/res/values/strings.xml

 Fixes  #386: Proper message is displayed at the end of sign up.

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/res/values/strings.xml

Fixes  #386 : Error message issue

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/ChangePasswordActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/ForgotPasswordActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java
app/src/main/java/org/fossasia/susi/ai/rest/model/ForgotPasswordResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/model/ResetPasswordResponse.java
app/src/main/res/layout/activity_change_password.xml
app/src/main/res/layout/activity_forgot_password.xml
app/src/main/res/values/strings.xml

Fixes issue #192: Implementation of Forgot Password

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #400 
Changes:  Action map is added for map response.

Fixes #400: Issue regarding showing of map in chat.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/rest/LocationClient.java
app/src/main/java/org/fossasia/susi/ai/rest/LocationService.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java
app/src/main/java/org/fossasia/susi/ai/rest/model/LocationHelper.java
app/src/main/java/org/fossasia/susi/ai/rest/model/LocationResponse.java

Fixes issue #372 
Changes: Added geolocation to susi api call.

Fixes #372 : Added geolocation to susi api call

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/model/Action.java

Fixes issue #419 and #372 and #397

Fixes issue #419 and #397: Add action type 'anchor' and fixed displaying messages with correct values

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/WebSearchHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/rest/BaseUrl.java
app/src/main/java/org/fossasia/susi/ai/rest/WebSearchApi.java
app/src/main/java/org/fossasia/susi/ai/rest/WebSearchClient.java
app/src/main/java/org/fossasia/susi/ai/rest/model/RelatedTopics.java
app/src/main/java/org/fossasia/susi/ai/rest/model/WebIcon.java
app/src/main/java/org/fossasia/susi/ai/rest/model/WebSearch.java
app/src/main/res/layout/activity_websearch.xml
app/src/main/res/values/strings.xml
build.gradle

Fixes #360 : Issue regarding websearch

---

app/src/debug/AndroidManifest.xml

Fixes #417 : Issue regarding loss of data on change of orientation

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/MapHelper.java

Small Typos Fix

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #427 
Changes: Google search feature added.

Fixes #427 : Google search feature added

---

app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #426
**Changes**
I have added a new Preference Screen titled 'Rate Susi'. When user clicks on it, It
will take the user to the Playstore link of Susi.
Thanks.

Fixes #426. Added a rate susi feature in the Settings Activity.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #415
Please refer to #425 for the screenshots.

Fixes #415 Added the new action call.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #443 : 
1. Fixed the crashing of app when someone asks "Where am I"
2. Added the "My location address" when someone asks "Where am I"

Fixes #443: Fixed the crashing of App and Added the myLocation Address

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/DateViewHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/date_view.xml

Fixes issue #255
Changes: Fixed date display feature

Fixes #255 : Fixing Date display feature

---

app/build.gradle
exec/apk-gen.sh

Fixes #448:Issue with APK downloading resolved.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/drawable/rounded_layout.xml
app/src/main/res/layout/activity_main.xml

Fixes issue #414 
Changes: AskSusiSomething EditText and Mic hides on tapping the search icon.

Fixes#414:AskSusi EditText and Mic Hides on search

---

exec/apk-gen.sh

Fixes issue : This fixes the large repo size due to APK branch. After this , only current apk and no old revisions will be kept so repo size will remain under 100mb which is currently ~2GB.

Improved apk upload script

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
build.gradle
circle.yml

Fixes issue #211 : It solves the issue of reloading of Link Preview view when it is brought back in view.
Changes: The Message Model was updated to include webpreview info so it is not loaded again and again using jsoup but only once.

Fixes #211: Link Preview View reloading resolved

---

app/src/main/java/org/fossasia/susi/ai/model/WebLink.java
circle.yml

Fixes Circle Failing Build. Please don't merge until build passes. I'll be amending the commit. Thanks.

Circle Fix for failing build after WebPreview Fix Merge

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/model/WebLink.java
app/src/main/res/values/strings.xml

Fixes #455:Google Search Intent triggering in unintended cases resolved.

Fixes #455: Google Search Intent triggering in unintended cases resol… .

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/model/WebSearchModel.java

Fixes #459: All prev web search results reflect the latest one only, issue resolved.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/values/strings.xml

Fixes #464 : Now alarm can be set from the app itself.

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Fixes issue #445 
Changes: 
Landscape layout for signup screen added.

Fixes #445:Adding landscape layout for signup screen

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml

Fixes #463 Share App feature

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes  #471 
Changes: Now the typing dots will be shown only after users message gets delivered to the server and hides after reply is set to the recyclerview.
however, dots are noticeable only if server takes some time give response back just like Allo.

Fixes #471 Fixed typing dots

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/values/strings.xml

Fixes issue #467 
Changes: Now reminder can be set from the app itself.

Fixes #467 : Now the reminder can be set from the app itself. 

---

app/src/main/res/layout-land/activity_change_password.xml
app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_change_password.xml
app/src/main/res/values-w820dp/dimens.xml
app/src/main/res/values/dimens.xml

Fixes #479 : UI improvement for landscape mode.

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Fixes issue #481 
Changes: Changed the email text to lowercase before making network call so that user can enter email in any case,
Screenshots for the change: Not required.

Fixes issue #481 Removed case sensitivity of email from the login form.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes  #486 : App crashing issue resolved.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/values/strings.xml

Fixes #485 : Now email can be send from the app itself.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #493
Changes: Voice reply now working fine for every query

Fixes #493 : Voice reply issue resolved .

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #507 
Changes: if backPressedOnce is true, return after calling finish().

Fixes #507 : Toast issue resolved now toast is displayed only once

---

app/src/main/res/values/strings.xml

made changes to certain items in strings.xml.

Fixes #517 : changed certain fields in strings.xml to non-translatable

---

gradle.properties

Fixes issue #510 
Changes: enhanced the gradle properties

Fixes #510 : reduce the build time

---

app/src/main/res/layout/activity_main.xml

Made changes to the chat ui as mentioned in the issue.

Fixes #521 : changed the chat ui

---

README.md

Fixes issue #534 
Changes:Added link to LICENSE.md

Fixes #534 Add link to License.md.

---

app/src/main/res/layout/activity_main.xml

Fixes issue #544 
Changes: Added `android:scrollbars="vertical"` in `activity_main.xml`
@jig08 @the-dagger Please review!

Scrollview in the message text box for multi line messages added.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #512 
Changes: TextToSpeech.OnInitListener() delays for the first time. So initialised it in the beginning itself. It fixed the delay. And reformatted the code.

Fix #512 delay in TTS fixed

---

app/src/main/java/org/fossasia/susi/ai/activities/ImportantMessages.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/drawable/ic_star_off_white_24dp.xml
app/src/main/res/layout/activity_important_messages.xml
app/src/main/res/menu/menu_selection_mode.xml
app/src/main/res/values/strings.xml

Fixes issue #568 
Changes: Added a feature to mark messages as unimportant. 

Fix #568 : Adding Feature to unmark messages

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

made changes as shown in the issue.

fixes #533 : changes to the chat message in MainActivity

---

README.md

Fixes issue #573 
Changes: 
- Fix formatting
- Fixed links

Fixes #573: Fix ReadMe formatting and links

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #570 
Changes: added code for checking if data size is greater than 0 or not. if it is then it will be deleted otherwise not.

fixes #570: App crashing in important messages activity

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java

Fixes issue #575
Changes: Language object added in the API call.

Fixes #575 : Language added to the API call .

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/PieChartViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultsHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/WebSearchHolder.java
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/layout/item_websearch.xml

Fixes issue #571 
Changes: Added star in the chat view holder for the messages which are marked as important.

Fixes #571 : Added star in important messages

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/layout/item_websearch.xml

Fixes issue #567
Changes: Corrected the click listeners on the view holders. Earlier, the user wasn't able to select either map view holder or link view holder or web view holder. Corrected these.

Fixes #567 : Corrected click listeners on view holders

---

app/src/androidTest/java/org/fossasia/susi/ai/TestLoginActivity.java
app/src/debug/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/java/org/fossasia/susi/ai/activities/ForgotPasswordActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.java
app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_forgot_password.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes issue #520 
Changes:Added a feature in which user can either select susi default server or a his own server.
EDIT : Changed the unit test accordingly.

Fixes #520 : Adding feature to select server

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/rest/WebSearchClient.java

Fixes issue #590 
Changes: Fixed the web search result. 

Fixes #590 : Fixed web search result

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/ImportantMessages.java

Fixes issue #595 
Changes: added back button and it's functionality

Fixes #595: back button in Important messages activity

---

app/src/main/AndroidManifest.xml

Fixes issue #598
Changes: changePasswordActivity removed from AndroidManifext.xml file.

Fixes #598 : ChangePassword activity removed from manifest

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #602 
Changes: Removed delay (https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L857) and anchor (https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L1009) for now as they are never being used. Removed loop here (https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L852)  as it was not required. Corrected waiting dots. 
@mayank408 @betterclever @amitiwary999 Can you test it?

Fixes #602 : Improved implementation of parsing json

---

app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_forgot_password.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

When signing up I found that all radio buttons where black and not that visible in the dark theme of the app. 
Changes: Made the Radio Buttons White
<table>
<tr>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/25632179/528c445c-2f90-11e7-9f58-1cdbb6380902.png" width="320px">
</td>
<td><img src="https://cloud.githubusercontent.com/assets/14369357/25632184/5847bf5c-2f90-11e7-8dce-21dfe7198041.png" width="320px">
</td>
</tr>
</table>

Change color of radio buttons at Login/Signup and Forgot Password

---

app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java
app/src/main/res/values/strings.xml

Fixes issue #[607], Linked with issue [#180](https://github.com/fossasia/susi_server/issues/180) (susi_server).
Changes: 
made regex simpler to allow any password with minimum 6 letters.

fixes #607: made password regex simple

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/rest/SusiService.java
app/src/main/java/org/fossasia/susi/ai/rest/model/MemoryResponse.java
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Fixes issue #633
Changes: Adding feature for retrieving old chat messages using memory.json
Used a dialog box to confirm from user if she wants to retrieve her messages.

Fixes #633 : Adding feature for retrieving old chat messages

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/MainApplication.java

Fixes issue #624 
Changes: Added leak canary for memory leak detection

Fixes #624 : Leak Canary enabled

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #619 
Changes: In the first run after installing app, the voice output was not working. Fixed it.

Fixes #619 : Voice output for voice input pref fixed

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultsHolder.java
app/src/main/res/layout/item_susi_image.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_image.xml
app/src/main/res/layout/search_item.xml
app/src/main/res/layout/search_list.xml

Fixes issue #611 
Changes: Removed dependency of ChatMessageVIew by replacing it with CardView.

Removing dependency of ChatMessageView

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/drawable/ic_close_24dp.xml
app/src/main/res/drawable/round_background.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml

Fixes issue #616 
Changes:  Implemented speech to text similar to google now, i.e speech is converted to text while the user is speaking.
@mariobehling @Orbiter @mayank408 @amitiwary999 @betterclever can you test this. Link for apk https://drive.google.com/file/d/0B6IO4qTKhVUCMFhScFpWTVpMblk/view?usp=sharing . Uninstall previous version of app before installing.

fix: Add feature to display partial speech to text results

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #637 
Dialog box is removed from asking the user for getting old messages. Now the previous messages will be automatically loaded in the chat.

Dialog box is removed from asking the user for getting old messages.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/release/java/org/fossasia/susi/ai/rest/ClientBuilder.java

Fixes issue #632 
Previously the app was crashing on playing videos due to link issues present in the answer. Fixed this now working fine.

Issue of app crashing while playing video is resolved and fixing Circle CI build failure

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #656 
Changes: Add a html escape sequence filter before adding message to the database.

Fix #656: Remove html escape sequences from responses

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/res/layout/activity_main.xml

Fixes issue #665 
Changes: Made the input text field expand upto 4 lines, and fixed problem with enclosing frame's width.

fix: UI issue with input text field

---

app/src/androidTest/java/org/fossasia/susi/ai/TestLoginActivity.java
app/src/androidTest/java/org/fossasia/susi/ai/test/MainActivityTest.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/MessageViewHolder.java
app/src/main/java/org/fossasia/susi/ai/helper/AndroidHelper.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Identity.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/LoginResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/MemoryResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metadata.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Session.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SignUpResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SusiResponse.java
app/src/main/res/layout/activity_main.xml

Fixes issue #645 
On running Android lint test some bugs and issues were reported which are rectified in this PR.

Small errors and probable issues found in the lint test are rectified.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SelectableAdapter.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Datum.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Identity.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/LoginResponse.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metadata.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SusiResponse.java

Fixes issue #658 
Changes: Changed Boolean to boolean

fix : Changed all Boolean to boolean 

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/MediaUtil.java

Fixes issue #657 
Changes: Added a check to see if recognizer is null.

fix: Fixes crash when voice input is closed

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fix : html parsing not implemented correctly in android

---

app/src/main/res/layout/search_item.xml

Fix issue with websearch layout.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.java

Fixes issue #697 
Now the date of the retrieved messages is set according to the query date coming from the response from the server.

Fix issue with date of retrieved messages.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fix : add anchor action type

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fix issue about having different menu options based on action type of response (Part 1 of 2)

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java

Fixes issue #698 
Now deleting messages as the user Login in the app.

Issue with retrieved messages solved.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #717 (some methods were left to be removed)
Some function related to important messages were left that are deleted in this PR.

Unnecessary function removed.

---

app/src/main/java/org/fossasia/susi/ai/activities/ForgotPasswordActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SignUpActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/AlertboxHelper.java
app/src/main/res/values/strings.xml

Fix : Reduce codacy issues

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/WebSearchAdapter.java

Fix : App crashes sometimes in case of websearch and rss action type

---

app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_piechart.xml
app/src/main/res/layout/item_user_link_preview.xml

Fixes issue #737 
Making all the elements left aligned in the UI.

UI fix: Elements aligned left side

---

app/src/main/res/layout/activity_main.xml

Fixes issue #740 
Changes: Position of scroll button is corrected.

Fix : Position of scroll button during search action is corrected.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #734 
Changes: Following these two links, I have used application context to fix these leaks.
1. https://github.com/square/leakcanary/issues/393#issuecomment-172640766
2. https://stackoverflow.com/questions/42089946/leaks-com-myapp-mainactivity-instance-6-9mb

fix : memory leaks in location and connectivity manager

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/RssViewHolder.java
app/src/main/java/org/fossasia/susi/ai/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Datum.java
app/src/main/res/layout/rss_item.xml
app/src/main/res/values/strings.xml

Fix : update rss action type

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #747 
Changes: request focus on search textview

Fix : cursor in searchview not working properly

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #744 
Changes: Added LinkMovement Method.

fix : Anchor link fixed

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/ConstraintsHelper.java

Fixes issue #760 
Right margin is added to the websearch.

Fix : Added margin to the websearch.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/res/menu/menu_selection_mode.xml
app/src/main/res/values/strings.xml

Fixes issue #755
Delete option is removed from the app as it is not implemented in server.

Fix : Removed delete option.

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #751 
Changes: request focus when voice input hide.

Fix : issue with chatmessage edittext

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fix : issue with preview in map action type reply

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/menu/menu_main.xml
app/src/main/res/values/strings.xml

Fix : implement anonymous mode

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fix : tts is not working properly

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fixes issue #731
Added checks for null values in the link preview.

Fix : Issues with views of LinkPreview is resolved.

---

app/src/main/java/org/fossasia/susi/ai/activities/LoginActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.java

Fix : Reduce codacy issues(part 2) 

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #736 
Changes: Passed websearch query string as a parameter to updateDatabase method because it was changing before database update.

fix : Adding websearch string as a parameter of the updateDatabase method

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java

Fix : app crashes after logout

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java

Fixes issue #779 
Changes: Changed the check inside the if statement.

Fix : Crash due to onRequest Permission method.

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/PieChartViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/SearchResultsListHolder.java
app/src/main/res/layout/item_susi_message.xml

Fix : reduce chatfeedrecycleradapter complexity

---

app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java
app/src/main/java/org/fossasia/susi/ai/activities/SettingsActivity.java
app/src/main/res/layout/alert_change_server.xml

Fix : issue with change server in case of anonymous mode

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SearchResultsAdapter.java

Fix : App is crashing after logging in

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt

Fixes issue #817
Changes: Implemented onDetach Method in Login and Signup Activities to avoid memory leaks.

Implemented onDetach Method in Login and Signup Activities

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt

Fix : softkeyboard done key not performing any action in loginactivity

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/SearchResultsAdapter.java

Fix : app is crashing in case of rss action type

---

app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/res/layout/item_susi_link_preview.xml

Fix : html tags are not parsed correctly in case of answer action type

---

gradle.properties

Fixes issue #863 
Changed the memory requirement in the jvm instance for fixing Circle CI

Fixing Circle CI

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/helper/MapHelper.kt
app/src/main/res/drawable/ic_scroll_to_end.xml
app/src/main/res/drawable/rounded_layout.xml
app/src/main/res/drawable/rounded_layout_green.xml
app/src/main/res/drawable/rounded_layout_grey.xml
app/src/main/res/layout/date_view.xml
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_map.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml
app/src/main/res/layout/item_waiting_dots.xml
app/src/main/res/layout/rss_item.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml

Fixes issue #870 
Changes: 
1. Changed Chat Bubble Layout 
2. Background color
3. Map and Link Views
4. Timestamp and Dateview
.
.
.
.
.

ui: fixes Chat Bubble Layout and Background

---

app/src/main/res/values-pt-rBR/strings.xml

Just added a brazilian portugueses translation.

Add Brazilian Portuguese Translation (PT-BR).

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/contract/IChatView.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.kt

Fixes issue #853  
Added language to TTS

fix: Changing language in TTS

---

app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
app/src/main/java/org/fossasia/susi/ai/data/LoginModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/data/db/contract/IDatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/data/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRatingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/res/drawable/thumbs_down_outline.xml
app/src/main/res/drawable/thumbs_down_solid.xml
app/src/main/res/drawable/thumbs_up_outline.xml
app/src/main/res/drawable/thumbs_up_solid.xml
app/src/main/res/layout/item_susi_link_preview.xml
app/src/main/res/layout/item_susi_message.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #840 
Changes: Add feedback feature.
.

feat: Add feedback feature

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SettingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/UtilModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISettingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IUtilModel.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Settings.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/settings/SettingsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/settings/contract/ISettingsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/settings/contract/ISettingsView.kt
app/src/main/res/values/array.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes #845 
1. add set query language option in android
2. Updated end point and settings keys to store settings on the server

Feat: add set query language option in android

---

app/src/main/java/org/fossasia/susi/ai/data/UtilModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IUtilModel.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/settings/SettingsPresenter.kt

Fixes #891 
Changes: storing setting for the anonymous user using different sharedpreferences key.

Feat: Store user setting in case of anonymous mode

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt

Fixes #904 
Added try catch to prevent app crashing due to inconsistent history,

fix: Crashing of app due to inconsistent history

---

app/build.gradle
build.gradle

Fixes #912 
Changes:
Updates realm plugin to 3.5 
switches from apt to kapt
Removes unrequired android apt plugin

Updates Realm plugin to 3.5 (With the issue resolved)

---

app/src/androidTest/java/org/fossasia/susi/ai/TestChatActivity.java

Fixes #928 
Changes : Removed old UI test to fix Circle build.

fix: Removed obsolete test to fix Circle build

---

README.md

Fixes #936 
Changes: edited roadmap in readme

Updated roadmap in documentation

---

app/src/main/res/layout/rss_item.xml

Fixes #948 
Changes: Description Text is shown correctly now. The text is not getting trimmed at bottom.
@chiragw15 please review this PR

Fix: RSS item Layout (Web Search)

---

app/src/main/AndroidManifest.xml

Updated Manifest File To Prevent App Crash At Try It

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #962 
Changes: Stop voice output on button press if textToSpeech is speaking

fix: Make Susi stop talking when the mic icon is pressed

---

app/build.gradle
app/src/main/AndroidManifest.xml

Increased version code and fix manifest file. Should be merged before #973

chore: increase version code and fix manifest

---

app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml

Fixes #1006 
Changes: App name is now SUSI AI

Fix #1006 - App name changed to SUSI AI

---

app/build.gradle

Fixes #1011 
Changes: 
- Increment version code and name for release v6

chore: Release v6: Increment versionCode

---

app/src/main/res/layout/item_skill.xml

Fixes #987 
Changes: Added Roboto font following material guidelines. 
*Ripple effect*
*Font Changes*
Before
After
**NOTE: The changes of screenshot of font changes are from Samsung galaxy s3 neo running android 5.1.1**

Enhanced susi skill frontend

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java

Fixes #1005 
Changes: Storing the result in sharedPreference and the user is notified only once.

Fixes #1005 Hotword detection Toast occuring for every instance

---

app/src/main/res/layout/item_user_link_preview.xml
app/src/main/res/layout/item_user_message.xml

timestamp below text message

---

app/build.gradle
app/src/androidTest/java/org/fossasia/susi/ai/LoginViewTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/TestChatActivity.java
app/src/androidTest/java/org/fossasia/susi/ai/test/ChatActivityTest.java
build.gradle

Signed-off-by: Yahor Berdnikau <egorr.berd@gmail.com>
Fixes #1015 
Changes: grant permission for UI tests using [GrantPermissionRule](https://developer.android.com/reference/android/support/test/rule/GrantPermissionRule.html)

Fix permissions not granted for some UI tests.

---

app/src/main/res/layout/welcome_slide1.xml
app/src/main/res/layout/welcome_slide2.xml
app/src/main/res/layout/welcome_slide3.xml
app/src/main/res/layout/welcome_slide4.xml

fix: 1022 welcome description overlap

---

app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/activity_welcome.xml
app/src/main/res/layout/alert_change_server.xml

It is a good practice and Android Studio also suggests it to support right to left layout .The alignparentRight line can not be deleted as end and start are not supported below api 17.

Added alignParentEnd  and alignParentStart to support Right to Left layouts

---

README.md
app/src/main/res/values-hi/strings.xml

Fixes #1064 
Changes:  
Add hindi localization.
Added values-hi/strings.xml

Add hindi localization

---

app/src/main/res/values/strings.xml

Fixes broken upstream strings on Weblate.

Language rework

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1009
Changes: Added Color to the skill rating based on their value

Added Rating color

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/res/drawable/ic_close_search.xml
app/src/main/res/drawable/ic_open_search.xml
app/src/main/res/layout/search_bar.xml
app/src/main/res/menu/skills_activity_menu.xml

Fixes #1078 
Changes: I've added a search bar in SkillsActivity. The user can search for a particular skill and the search bar will automatically scroll to it.

Added search bar in skills activity

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/res/layout/fragment_skill_listing.xml

Fixes #1091: Add Refresh Layout for Skills Fragment

---

app/config.gradle

Fix #1094: Upgrade Kotlin Version

---

app/src/main/AndroidManifest.xml

Fixes #1127 
Changes: Soft-keyboard automatically pops up when the enter email Edittext gets focus.

Fix #1127-Reset password page edittext issue resolved.

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml

Fixes #1126 
Changes: Soft-keyboard automatically pops up when the Edittext to enter email receives focus.

Fix #1126-Edittext issue in the login page fixed.

---

app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1111 
Improved skill details rating ui by arranging the positive and
negative ratings in a horizontal fashion.
**Screenshots for the change:** 
**Original**
**Final**

Improved skill details rating UI (Fixed #1111)

---

app/src/main/res/values/dimens.xml

Sorted dimens in dimens.xml by name using AndroidXmlSorter plugin.
Fixes #1125 

Sorted dimens resource values by name (Fixed #1125)

---

app/src/androidTest/java/org/fossasia/susi/ai/chat/ChatActivityTest.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/contract/IChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_login.xml

Fixes #1166 
Changes: Removed the toast message that was being displayed to prompt the user before exiting from the app as that might break user experience.

Removed confirmation before exit (Fixed #1166)

---

app/src/androidTest/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/login/LoginActivityTest.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/values/strings.xml

Replaced hard-coded strings in SkillDetailsFragment.kt by Android
resource strings and used append instead of '+' for string concatenation
in setText as there could be translation issues otherwise.
Fixes #1134

Used android resources for strings in setText (Fixed #1134)

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/data/ForgotPasswordModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SettingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IForgotPasswordModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISettingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/data/db/contract/IDatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordPresenter.kt
app/src/main/java/org/fossasia/susi/ai/helper/ChatBubbleLayout.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/SettingsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

This pull request renames class names and variables that are not in accordance with java conventions. No changes occur in the way the app appears or functions.

Rename variables in accordance with java conventions

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #1243 
Changes: Removed menu present in ChatSettingsFragment.

Remove menu from ChatSettingsFragment (Fixed #1243)

---

app/src/main/res/layout/alert_reset_password.xml

Fixes #1209 
Changes: Added the scrollview to scroll the dialog in landscape mode.

Added scrollview to fix dialog

---

app/src/main/java/org/fossasia/susi/ai/login/WelcomeActivity.java

Fixes #1083 
Changes: Using PrefManager class instead of creating separating Preference object

Using PrefManager class instead of creating separating Preference object

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/res/values/strings.xml

Fixes #1240 
Changes: Added a toast message if no skill is found in the app on searching

Added message if no skill is found

---

app/src/main/res/values/strings.xml

Sorted strings resource values present in strings.xml by name using
AndroidXmlSorter plugin.
Fixes #1124 

Sorted strings in strings.xml by name (Fixed #1124)

---

circle.yml

Removed the connectedCheck

---

app/src/main/res/values/strings.xml

Fixes #1262 
Changes: Added a missing string resource value.

Fixed app crash on scrolling through Skills Activity (Fixed #1262)

---

app/src/main/res/layout/item_susi_link_preview.xml

Fixes #1148 
Changes: Replaced hard-coded string by string resource value.

Replaced hard-coded string by string resource value (Fixed #1148)

---

app/src/main/res/values/strings.xml

Fixes #1263 
Changes: Added a few missing strings in strings.xml.

Fixed app crash on opening Settings (Fixed #1263)

---

app/build.gradle
app/config.gradle
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/data/db/contract/IDatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/SkillExamplesAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillGroupAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/res/xml/pref_settings.xml
build.gradle
circle.yml
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Fixes #1194
Changes : Updated :-
* Android Gradle plugin to 3.1.2
* Android Gradle version to 4.7
* Kotlin plugin to 1.2.41
* compileSdkVersion to 27
* targetSdkVersion to 27
* Support Library version to 27.1.1
* Preference version to 27.1.1.1
* LeakCanary version to 1.5.4
* Butterknife version to 8.8.1

Updated Gradle (Fixed #1257)

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Remove reductant code in ChatActivity.kt

---

exec/apk-gen.sh

Fix the app location of generated apk

fix: Correct apk location

---

app/build.gradle

- Increment version before app release

chore: Increment version 7 - v1.0.6

---

exec/prep-key.sh

chore: Change default message digest to MD5

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/ai/kitt/snowboy/Constants.java
app/src/main/java/ai/kitt/snowboy/SnowboyDetect.java
app/src/main/java/ai/kitt/snowboy/audio/RecordingThread.java
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/layout/activity_device.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml
exec/prep-key.sh

chore: Merge dev into master

---

app/src/main/java/org/fossasia/susi/ai/forgotpassword/ForgotPasswordActivity.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/layout-land/activity_forgot_password.xml
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_forgot_password.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/alert_change_server.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml

Fixes #1192 
Changes: changed customer server to custom server

Replaced Customer server with custom server

---

app/config.gradle
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/PieChartViewHolder.java

Fixes #1307 
Changes: Updated the MPAndroidChart library version to v3.0.3)

Update MPAndroidChart library version to v3.0.3 (Fixed #1307)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/XAxisValueFormatter.java
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1324  [Parent issue #1270 ]
Changes: Add Skill Ratings chart in place of existing rating in SkillDetailsFragment.

Add UI to display five star and average rating in Skill Details page (fixed #1324)

---

app/src/main/java/ai/kitt/snowboy/AppResCopy.java
app/src/main/java/ai/kitt/snowboy/audio/AudioDataSaver.java
app/src/main/java/ai/kitt/snowboy/audio/RecordingThread.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/WebSearchAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/login/WelcomeActivity.java

Fixes #1317 [Parent #1311 ]
Changes: Added appropriate annotations and checked for nullability conditions, wherever required.

Fixed probable bugs (Fixed #1317)

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #1244 
Changes: Removed the keyboard hiding code

Keyboard visible on pressing cross on SkillsActivity

---

app/build.gradle
app/config.gradle
app/src/androidTest/java/org/fossasia/susi/ai/chat/ChatActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/login/LoginActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/login/WelcomeActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/signup/SignUpActivityTest.kt
app/src/androidTest/java/org/fossasia/susi/ai/skills/SkillsActivityTest.kt
app/src/main/java/ai/kitt/snowboy/AppResCopy.java
app/src/main/java/ai/kitt/snowboy/audio/AudioDataSaver.java
app/src/main/java/ai/kitt/snowboy/audio/RecordingThread.java
app/src/main/java/org/fossasia/susi/ai/MainApplication.java
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/WebSearchAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/SearchResultsListHolder.java
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #1334 
Changes: Used Timber for logging in place of Android logging framework.

Use Timber for logging (Fixed #1334)

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/activity_device.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/fragment_skill_listing.xml
app/src/main/res/layout/fragment_sttframe.xml

Fixes #1330 
Changes: Added all the view items as camelCase

Converted view items to camel Case

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

Social Skills group is shown only once

---

app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/values/strings.xml

Fixes #1290 
Changes: Updated dialog message strings to show standard messages and actions.

Modify dialog messages to display standard messages (Fixed #1290)

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillFragmentCallback.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillGroupAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

Fixes #1339 
Changes: hid the keyboard and enabled the title before loading the fragment
@iamareebjamal @batbrain7 please review

Fixed #1339: Search bar appears in Settings

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MapViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/PieChartViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/SearchResultsListHolder.java
app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/helper/AndroidHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/LocationHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/MediaUtil.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/rest/clients/BaseUrl.java

Fixes #1314 
Logged the exceptions using Timber

Logged the caught Exceptions

---

app/src/main/java/org/fossasia/susi/ai/helper/Constant.java
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt

Fixes #1171 
Changes: 
Dialog in the SignUp activity is retained even after configuration change.

Retained the dialog in SignUp activity

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VerticalRecyclerAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/VerticalCellViewHolder.java
app/src/main/res/layout/table_recylcer_item.xml

Fixes #1360
Changes: Added the links in the table action type responses.

Added the links in the table response now

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/FiveStarSkillRatingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillData.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/FiveStarSkillRatingRequest.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/strings.xml

Fixes #1359 
Changes: Now, the user can send five star rating to the server.

Send five star rating to the server (#1359)

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/TableAdapter.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VerticalRecyclerAdapter.java
app/src/main/res/layout/susi_table.xml
app/src/main/res/layout/table_recylcer_item.xml

Added the chromeTab for links in table response and made table response background white

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.java

Fixes #1397 
Changes: Now the app responds with a query whenever an audio or video action is parsed.

Caught the "audio_play" and "video_play" action types

---

app/build.gradle

Fixes #1302 
Changes : updated the version code and name for the fdroid apk and the playstore apk

Update the version code and name

---

exec/apk-gen.sh

Update apk-gen.sh script

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IChatModel.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
exec/apk-gen.sh

Changes: Merge the dev to master

Update apk-gen to release new version

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/data/ChatModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IChatModel.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java

Fixes #1394 
Changes: Now country code and name is also sent as a query in chat.json API.

Send country code and name in chat.json API (Fixed #1394)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillViewHolder.java
app/src/main/res/layout/item_skill.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

Fixes #1401 
Changes: Display average stars and total ratings on skills home page
**New**
**Old**

Display average rating on skills card (Fixed #1401)

---

app/src/main/java/org/fossasia/susi/ai/data/SkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/FiveStarSkillRatingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetRatingByUserResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Ratings.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/FiveStarSkillRatingRequest.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsView.kt

Fixes #1421 
Changes: Show the updated rating by the user on the rating bar.

Display rating by user on the rating bar

---

app/src/main/java/org/fossasia/susi/ai/MainApplication.java

Fixes #1425 and #1426 
Changes: Replaced timber with log in MainApplication.java file

Use Log in place of Timber in MainApplication

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/device/DevicePresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/contract/IDevicePresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/contract/IDeviceView.kt
app/src/main/res/values/strings.xml

Fixes #1420 
This PR scans the wifi networks nearby and then stores the detected Wireless access points.

Susi smart speaker access point is detected

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SearchResultsAdapter.java
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt

Fixes #1430 
Removed variables from DatabaseRepository that were causing lint issues

Remove variables from DB

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1432 
Changes: Fixed app crash.

Fix app crash in skill details screen (Fixed #1432)

---

app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillData.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillGroupAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/contract/ISkillListingView.kt

Fixes #1412 
Changes: Display skills in the descending order of top ratings.

Display skills list in the descending order of top ratings (Fixed #1412)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/res/layout/item_skill.xml
app/src/main/res/values/strings.xml

Fixes #1434 
Changes: Added null checks to avoid app crashes due to null values received during API calls.

Add null checks for skill ratings object (Fixed #1434)

---

app/build.gradle
app/config.gradle
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java
build.gradle

Fixes #1440  
Parent issue : #1302
Changes: Removed the link preview library that was already present and added an alternative library that can be acceptable for FDroid.

fix:Replace the link preview library 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt

fix: Remove quotes from environmental variable

---

app/build.gradle

Changes: Update for the new version on the playstore

chore: updated version code and name

---

app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt

Fixes #1461 
Changes: Opposite logic was present in the YoutubeActivity.kt file to play the youtube videos.
Now the whenever key is present we can play videos

fix: Environment variable is used now

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #1463 
Changes: Added currentfocus not null.

fix: Settings crash due to null currentfocus

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1486 
Changes: Removed extra call to setRating()

Removed extra call to setRating() (Fixed #1486)

---

app/src/main/java/org/fossasia/susi/ai/data/SkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/PostFeedback.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/PostSkillFeedbackResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsView.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1442 [Parent issue #1388 ]
Changes: The user can now post feedback for any skill.
The current UI for feedback section:

Allow the user to post feedback for a skill (Fixed #1442)

---

app/src/main/java/org/fossasia/susi/ai/MainApplication.java
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/YoutubeVideoViewHolder.java
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1495 
Changes: Fixes for API level less than 21.

fix:  Solve crashes for API level less than 21

---

app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt

Fixes #1482
Changes:  Many action types are not supported by the server, so it is removed.

fix: Remove unsupported action types

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/res/layout/activity_chat.xml

Fixes #1476 
Changes:Added to not show suggestions.
It has been working fine now on google keyboard too.

Enter as send working

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

Fixes #1464 
Changes: the UI was not getting updated once the "Unable to fetch data" was displayed , now the UI is updated so whenever we swipe down the UI is displayed properly.

fix: the skills will be fetched always if internet connectivity is there

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Fixes #1480 
Changes: Added null check for the five star rating bar. (Crash report can be seen in the linked issue)

Fixed app crash on tapping examples (Fixed #1480)

---

app/build.gradle

Update version 1.0.9 to 1.0.10
and version code to 11

chore : update version 

---

app/src/main/res/values/strings.xml

Fixes #1504 
Changes: Fixed typos mentioned in #1504

Fixed typos in welcome slides (Fixed #1504)

---

app/src/main/res/values/strings.xml

Fixes #1502
Changes: Changed app label from SUSI AI to SUSI.AI.

Changed app label from SUSI AI to SUSI.AI (Fixed #1502)

---

app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java

Fixes #1534 
Changes: These methods were called directly and that cause NPE

Fix #1534 Crash fix

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/WifiViewHolder.java
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectView.kt
app/src/main/res/layout/layout_wifi_item.xml
app/src/main/res/values/strings.xml

Fixes #1250 
This PR should not be reviewed on grounds for string resources and grammatical names as the strings will be deleted anyways, only the simplest connection possible is the aim of this PR.
A basic connection is established through the android app to the smart speaker. The API endpoints are hitting correctly, but due to recent code changes in the susi linux repository the code crashes on raspi, 
A follow up fixing PR has been sent for that by @stealthanthrax : https://github.com/fossasia/susi_linux/pull/258
here is the output  :

feat: make a basic device connection

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/res/values/strings.xml

Fixes #1533 
Review changes from PR #1533 and null receiver error fix.

 fix: receiver null error

---

app/src/main/java/org/fossasia/susi/ai/helper/SimpleDividerItemDecoration.java

Fixes #1543 
Changes: Removed Hungarian notation

Remove Hungarian notation (Fixed #1543)

---

app/src/main/java/org/fossasia/susi/ai/data/DeviceModel.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt

Fixes #1546 
Changes: Review fixes for the PR #1540

chore: style issues in device section

---

app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt

Fixes #1551 
Changes: the youtube video plays automatically now.

fix: automatic play on youtube

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml

Fix style issues in Android Manifest (Fixed #1553)

---

app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java

Fixes #1545 
Changes: Removed redundant and unused code from SusiService.java

Remove redundant and unused blocks of code from SusiService.java (Fixed #1545)

---

README.md

Fixes #1562 
Changes: update readme for youtube API key information

update readme for youtube api key

---

app/build.gradle

chore: Remove version id and name prefix

---

app/src/main/res/values/strings.xml

Replace latest by recently updated in the latest skills horizontal recyclerview (Fixed #1585)

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ChangeSettingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Feedback.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/FiveStarSkillRatingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ForgotPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetRatingByUserResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListGroupsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillMetricsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/MemoryResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metadata.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/PostSkillFeedbackResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Ratings.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ResetPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Session.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Settings.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SignUpResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRatingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Skills.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Stars.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SusiResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/UserSetting.kt
app/src/main/res/values/strings.xml

Fixes #1595 
Changes:made response class to data class

chore: convert response classes to data classes

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt

refactor: Remove redundant semi colons from DeviceConnectFragment.kt (Fixed #1602)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillMetricsAdapter.kt

Set CATEGORIES not clickable (Fixed #1605)

---

app/src/main/java/org/fossasia/susi/ai/helper/CircleTransform.java
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/viewholders/SkillViewHolder.java
app/src/main/res/layout/item_skill.xml
app/src/main/res/values/dimens.xml

Fixes #1520 
**Old UI**
**New UI**

Improve UI of skill cards (Fixed #1520)

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt

Handle unsafe class cast in DeviceConnectFragment

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1631 : Empty Feedback is not send
Changes: Trim method applied on string.

Fix:1631 Empty Feedback not sent

---

app/src/main/java/ai/kitt/snowboy/AppResCopy.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.java
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.java
app/src/main/java/org/fossasia/susi/ai/data/LoginModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SignUpModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/data/model/ChatMessage.java
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java

refactor: use timber in place of printStackTrace

---

app/src/main/res/values-hi/strings.xml

Add Hindi translations for String resources (Fixed #1609)

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ForgotPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListGroupsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/MemoryResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metadata.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ResetPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Session.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SignUpResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Skills.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Stars.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SusiResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/UserSetting.kt

Remove unused imports from susi response files (Fixed #1618)

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt

refactor: use appropriate variable names

---

app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Answer.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ChangeSettingResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Datum.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ForgotPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetRatingByUserResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/GetSkillFeedbackResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Identity.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListGroupsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ListSkillsResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/LoginResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/MemoryResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metadata.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Metrics.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Ratings.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ResetPasswordResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Session.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Settings.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SignUpResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillData.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SkillRating.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Skills.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Stars.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/SusiResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/UserSetting.kt

Use proper spacing in susi response files to make it consistent with other files (Fixed #1622)

---

app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt
app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/viewholders/AllReviewsViewHolder.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/viewholders/FeedbackViewHolder.java
app/src/main/res/layout/item_feedback.xml

Fixes #1637 
Changes: Now the user's avatar is displayed in feedback section.

Integrate gravatar for users in feedback section (Fixed #1637)

---

app/src/main/res/layout/item_skill.xml
app/src/main/res/layout/item_skill_group.xml
app/src/main/res/layout/item_skill_group_list.xml

Fixes #1523 
Changes: Made following changes:
* Changed font family
* Changed font color
* Adjusted padding
Before:
After:

Improve UI of skills listing page (Fixed #1523)

---

app/build.gradle

Update the version code and name.

chore: update version name and code

---

app/build.gradle
app/config.gradle
app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt
app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt
app/src/test/java/org/fossasia/susi/ai/helper/UtilsTest.kt

Fixes #1615 
Changes: Now the complete email is not shown. Rather, an email is truncated after '@' symbol.
**Screenshot**

Anonymize feedback and add unit tests for the method added to the UtilModel (Fixed #1615)

---

app/src/main/java/org/fossasia/susi/ai/skills/feedback/FeedbackActivity.kt
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/item_feedback.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1450 
Changes :
* Reduced the size of avatar.
* Changed the font family.
* Changed the background color from default to white.
* Added the title in the all reviews activity.
Before:
After:

Make feedback UI consistent with that of skills CMS (Fixed #1450)

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/res/layout/fragment_skill_details.xml

Remove unnecessary terms of use and developer's policy (Fixed #1664)

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/res/layout/fragment_device_connect.xml
app/src/main/res/values/strings.xml

fix: add the strings similar to google home

---

app/src/main/res/drawable/thumbs_down_outline.xml
app/src/main/res/drawable/thumbs_up_outline.xml

Thumbs up is changed to green
Thumbs down is changed to red
Fixes #1678 
Before:-
After:-

Thumb Outline Color Improved

---

app/build.gradle

Updated the version code to 14 and version name to 1.0.13.

chore: Update version code and name

---

app/src/main/java/org/fossasia/susi/ai/data/SkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillDetailsModel.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/ReportSkillQuery.kt
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.java
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ReportSkillResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.java
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/contract/ISkillDetailsView.kt
app/src/main/res/layout/alert_report_skill.xml
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/values/strings.xml

Fixes #1530: Added feature to report skills
Changes:
@arundhati24 @batbrain7 Please check!

feat: Add report skill feature for users

---

app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Feedback.kt
app/src/main/java/org/fossasia/susi/ai/skills/feedback/adapters/recycleradapters/AllReviewsAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt

Fixes #1723 
Before : 
After :

feat: Use SUSI API instead of Gravatar to display avatar

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt

Fixes #1713
Changes: Voice input is disabled until the previous input is running

fix: Fix multiple spawn of SpeechInputlistner

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

fix: Rearrange repositories source

---

app/src/main/java/org/fossasia/susi/ai/helper/Utils.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

fix: Hide soft keyboard after authentication

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

fix: Hide soft keyboard while closing search bar using icon

---

app/src/main/java/kotterknife/ButterKnife.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SelectionDialogListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/WebSearchAdapter.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/SearchResultsListHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/YoutubeVideoViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/helper/CredentialHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/LocationHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/login/WelcomeActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt

feat: Remove not-null assertions with safe calls

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md

chore: Update issue template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/feature_request.md

chore: Fix issue template

---

app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-land/activity_sign_up.xml
app/src/main/res/layout-land/fragment_skill_details.xml
app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/activity_forgot_pass.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/activity_welcome.xml
app/src/main/res/layout/alert_change_server.xml
app/src/main/res/layout/fragment_skill_details.xml
app/src/main/res/layout/fragment_sttframe.xml
app/src/main/res/layout/progress.xml
app/src/main/res/layout/rss_item.xml
app/src/main/res/layout/table_recylcer_item.xml
app/src/main/res/values/dimens.xml

Fixes #1120
Changes: Some dimensions in layout xml files had hard-coded dimensions. I replaced all hard-coded dimensions with dimens resource values.

fix: Replaced all hard coded dimension values with dimens resources values.

---

app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values/strings.xml

Fixes #[Completely solved issue 1845]
Changes: [made Changes in LoginPresenter.kt file and in all the strings.xml file]

fix: issue 1845

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #1812 
Changes: OnBackStackListener is add while onBackPressed where you have to press again to set the listener. But when it is set while onCreate then it will be called while onBackPressed

fix: Title changes in skills activity

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/menu/skills_activity_menu.xml

fix: Handle menu items for fragments in activity

---

app/src/main/res/layout/activity_login.xml

Fixes #1733 
Changes: Font of "Sign up for SUSI" on the login screen has been made same as other fonts.

fix: Corrected font of "Sign up for SUSI".

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/SelectionDialogListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/data/UtilModel.kt
app/src/main/java/org/fossasia/susi/ai/data/db/DatabaseRepository.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/helper/DateTimeHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/LocationHelper.kt
app/src/main/java/org/fossasia/susi/ai/helper/PrefManager.kt
app/src/main/java/org/fossasia/susi/ai/helper/SnackbarBehavior.kt
app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/java/org/fossasia/susi/ai/login/WelcomeActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/adapters/recycleradapters/SkillsListAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/FeedbackAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/adapters/recycleradapters/SkillExamplesAdapter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/adapters/recycleradapters/SkillListAdapter.kt

feat: Remove unsafe casting in favor of smart cast

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixes #1881 
Changes: build gradle of the app has been upgraded to 3.3.0 from 3.2.1 and kotlin-gradle-pluglin has been upgraded to 1.3.11 from 1.2.71.

chore: Upgraded gradle versions.

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatPresenter.kt
app/src/main/java/org/fossasia/susi/ai/chat/ParseSusiResponseHelper.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/TableAdapter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/recycleradapters/DevicesAdapter.kt

Fixes #1688 
Changes: Replaced all single character variable names with proper names.

fix: Replaced single letter variable names with proper names.

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/ChatFeedRecyclerAdapter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/WifiViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/playStore/java/org/fossasia/susi/ai/chat/YouTubeActivity.kt

Fixes #1888
Changes: 
Added strings in string resources
Changed the strings to use string resources for the added strings in resources

fix: Added string resources

---

app/src/main/java/org/fossasia/susi/ai/login/LoginPresenter.kt
app/src/main/res/values/strings.xml

Added relevant response when trying to log in with inactive account.

---

app/src/main/res/values/array.xml

feat: add option to select tamil

---

app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/res/values/strings.xml

fix: About us page now shows missing words

---

build.gradle

Build gradle updated from 3.3.0 to 3.3.1

feat: Build gradle updated

---

app/src/main/res/values/array.xml

Fixes #1932 
Changes:Language translation icon for Tamil changed to Tamil fonts

fix-1932:Changed language change option for Tamil

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #1927 Wrong variable name in comment
Changes:
Changed variable name

chore: Use correct variable name in doc comment

---

app/src/main/res/layout/activity_feedback.xml

Fixes #1930 Scroolbar in feedback activity
Changes: 
Added scrollbar in feedback activity

style: Add scrollbar in feedBack activity

---

app/src/main/res/values-hi/strings.xml
app/src/main/res/values-ml-rIN/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml

Changes: If the internet is off, skills activity is not showing that the reason for being unable to fetch skills can be due to the internet connection. It just shows that an error has occurred. So I've updated the message to point user to check internet connection.

chore(strings): updated error messages in multiple languages

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #1807 
Fixes #1780 
Fixes #1786 
Fixes #1898 
Changes: 
- Skip null permissions

fix: Check for null permission in onPermissionsResult

---

app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_skill_listing.xml

Fixes #1938 
Changes:Removed toggle password for confirm password field which now follows the standard criteria such that only show password toggle for password field not for confirm password.

fix: Remove toggle for confirm password field

---

README.md

Fixes #1987 
Changes: 
Update the link of espresso library in the readme file.

fix: Updated espresso link in readme file.

---

build.gradle

Changed gradle version from 3.3.1 to 3.3.2

chore: updated gradle version to 3.3.2

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/xml/pref_settings.xml

Fixes #2008 
Changes:
Changes are made in: 
* ChatSettingsFragment.kt
* pref_settings.xml

feat: Click on Not logged in to open login page

---

app/src/main/java/org/fossasia/susi/ai/login/LoginActivity.kt
app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values/strings.xml

Fixes #2009 
Changes: 
* LoginActivity.kt
* SignUpActivity.kt
* activity_sign_up.xml
* strings.xml

feat: Move from signup page to login page

---

app/src/fdroid/java/org/fossasia/susi/ai/chat/YoutubeVid.kt

Changes: I've improved the code of YoutubeVid.kt file according to the official coding guidelines.

chore: improve code style in YoutubeVid.kt file

---

app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/res/layout/fragment_about_us.xml
app/src/main/res/values/strings.xml

Fixes #2021 
Changes: 
* strings.xml
* AboutUsFragment.kt
* fragment_about_us.xml

feat: Added know more feature

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #2016 
Changes: 
SkillDetailsFragment.kt

feat: Move from feedback to signup

---

app/src/main/java/org/fossasia/susi/ai/skills/skilldetails/SkillDetailsFragment.kt

Fixes #2034 
Changes:skill detail fragment

fix: Move from feedback to login

---

app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ml-rIN/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml

Fixes #1985 
Changes: 
* Added the textview in SignUp page
* Added translations in string file
* Added the intent in SignUpActivity

feat: Added link to terms and condition in signup page

---

app/src/main/res/layout/activity_sign_up.xml

Fixes #2042 
Changes: 
* Added an image view in activity_sign_up.xml

feat: Added SUSI.Ai logo in signup page

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

Fixes #2035 
Changes: 
* Added preference in pref_settings
* Added the onClickListener in ChatSettingsFragment
* Added the strings in string file.

feat: Added feature to move from setting to about us

---

app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
app/src/main/java/org/fossasia/susi/ai/skills/aboutus/AboutUsFragment.kt
app/src/main/res/values/strings.xml

Fixes #2031 
Changes: strings.xml

fix: Correct the directing link of know more in about activity

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #2063 
Changes:
Added "Sign Up" option property setEnabled as false when user is logged in.

fix: Disable signup when logged in

---

app/src/main/res/values/array.xml

Fixes #2061 
Changes:
* Added the language in the arrays of the array file

fix: Add malayalam in ListPrefernce of settings fragment

---

app/src/main/res/values/strings.xml

Fixes #2079 
Changes:
Added the missing translation in default string file.

fix: Fix the app

---

app/src/main/java/org/fossasia/susi/ai/signup/SignUpActivity.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ml-rIN/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml

Fixes #2108 
Changes:
Created an alert dialog box.

feat: Alert dialog box on pressing skip in signup page

---

README.md

Fixes #2118
Changes: Changed the links in the README file

chore: update link in readme

---

app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VoiceCommandsAdapter.kt
app/src/main/res/layout/fragment_sttframe.xml
app/src/main/res/layout/item_voice_commands.xml
app/src/main/res/values/array.xml

Fixes #2092 
Changes: 
* User gets a set of commands to click in voice prompt.
* This commands are sample ones.
Future enhancement:
* Ui can be optimised later, when the entire code base is properly implemented.

feat: Modified voice layout.

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/res/layout/activity_chat.xml

Fixes #2155 
Changes: 
* Changed the if else condition in button press.

fix: Close chat search if user wants

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #2083 
Changes:skills activity

fix: Remove signup if user logged in

---

app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt

Fixes #2162 
Changes: chatsettings fragment

fix: Reset password option only in case of logged in

---

build.gradle

Fixes #2168 
Pr against : #2169 
Changes: Kotlin version updated

chore: Kotlin version updated

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/res/layout/fragment_skill_listing.xml
app/src/main/res/layout/skill_listing_placeholder.xml
app/src/main/res/values/colors.xml

Fixes #2090 
Changes: 
Instead of progress bar, it now displays a shimmer. Shimmer has become common in almost every app. So this feature was necessary

feat: Added shimmer effect in Skill List fragment

---

app/src/main/java/org/fossasia/susi/ai/skills/feedback/FeedbackActivity.kt

Fixes #2084 
Changes: 
Everything was already created. There was a minor error in the code logic. I have made the change and its working fine now.

fix: Contents shown in all reviews page

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-hi/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ml-rIN/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml

feat: Toast appears when user rates chat

---

app/config.gradle

Fixes #2209 
Changes:
Changed the gradle file. Also tested the app by running it.

feat: Changed minimum android version to v5.0

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/res/layout/fragment_group_wise_skill_listing.xml

Fixes #2208 
Changes: 
The search process has been implemented

feat: Search skills in category fragments

---

app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/skillSearch/SearchSkillFragment.kt
app/src/main/res/layout/fragment_group_wise_skill_listing.xml
app/src/main/res/layout/groupwise_skill_listing_placeholder.xml

Fixes #2200 
Changes: 
Instead of the progress bar, a shimmer effect rises in the GroupWise skill listing page.

feat: Shimmer effect in groupwise skills

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/DeviceViewHolder.kt

Fixes #2226 #2225 
Changes: 
After debugging the code base it was found that the onClick method was not initialized properly. In the pre-release version (java version of the code worked properly). After making minor changes, it has started working.

fix: Smart speaker is now connectable

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/res/layout/activity_chat.xml
app/src/main/res/values/strings.xml

Fixes #2219 
Changes: 
Implemented voice search of old chats in the chat activity. Users can search for old messages via voice search.

feat: Voice search implemented on chat

---

app/build.gradle
app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/adapters/viewholders/DeviceViewHolder.kt
app/src/main/res/layout/activity_chat.xml
app/src/main/res/values/strings.xml

Upgrading the app release version

chore: Release v1.2.0

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #2234 
Changes: [Add here what changes were made in this issue and if possible provide links.]

fix: fixed visibility of voice search icon in chat activity and stt fragment

---

app/src/main/res/layout-land/activity_sign_up.xml

Fixes #2039 
Changes: 
Added the missing parameters

fix: Fixed the crash of signup page in landscape mode

---

app/src/main/java/org/fossasia/susi/ai/chat/ChatActivity.kt

Fixes #2244 
Changes:
The problem was regarding the resetting of variable and removal of an intent value.

fix: Fix the bug in the try button of skill details page

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/res/layout/fragment_skill_listing.xml

Fixes #2138 
Changes:
Changed the layout height to match parent and used replace instead of add

fix: Resolve skill details page contraction

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/recycleradapters/VoiceCommandsAdapter.kt

fix: Fix voice commands actions in voice prompt window

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ImageViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/LinkPreviewViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/TableViewHolder.kt

Fixes #2254 
Changes:
Toast message was wrongly implemented. I have corrected it.

fix: Toast message in rating susi response

---

app/src/main/java/org/fossasia/susi/ai/chat/STTfragment.kt

Fixes #2143 
Changes:
Increased the time for listening to voice, if the user is silent for some time.
No relevant UI changes

fix: Increase voice detection time in voice message query

---

app/src/main/java/org/fossasia/susi/ai/rest/clients/LocationClient.kt
app/src/main/java/org/fossasia/susi/ai/rest/clients/WebSearchClient.kt

Fixes #2272 #2268 
Changes:
Changed the base urls http connections to https connection to avoid network security errors

fix: Change http to https to avoid connection errors

---

app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/ChatViewHolder.kt
app/src/main/java/org/fossasia/susi/ai/chat/adapters/viewholders/MessageViewHolder.kt
app/src/main/res/drawable/ic_resend.xml
app/src/main/res/layout/item_user_message.xml

Fixes #2260
Changes: 
Users can now resend a message just by clicking the resend icon beside the chat. Its a similar feature as that present in google assistance implemented in a different UI way.

feat: Resend message

---

app/src/main/java/org/fossasia/susi/ai/dataclasses/AddDeviceQuery.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt

Fixes #2280
Changes: 
Removed the excess occurrence of access_token parameter in the URL

fix: Remove excess access token occurrence

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectPresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/contract/IDeviceConnectPresenter.kt

Fixes #2277 
Changes: 
The actual location of the device is added to the server.

feat: Add location of the device

---

app/src/main/java/org/fossasia/susi/ai/data/contract/IRoomModel.kt
app/src/main/java/org/fossasia/susi/ai/data/device/RoomModel.kt
app/src/main/java/org/fossasia/susi/ai/device/DeviceActivity.kt
app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/ConnectedDeviceFragment.kt
app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/ConnectedDevicePresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/adapters/ConnectedDevicesAdapter.kt
app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/contract/IConnectedDevicePresenter.kt
app/src/main/java/org/fossasia/susi/ai/device/connecteddevices/contract/IConnectedDeviceView.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/ConnectedDevicesResponse.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Device.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Devices.kt
app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Location.kt
app/src/main/java/org/fossasia/susi/ai/rest/services/SusiService.kt
app/src/main/java/org/fossasia/susi/ai/skills/settings/ChatSettingsFragment.kt
app/src/main/res/layout/fragment_connected_device.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_settings.xml

feat: Display connected devices

---

app/src/main/java/org/fossasia/susi/ai/device/deviceconnect/DeviceConnectFragment.kt
app/src/main/res/values/strings.xml

Fixes #2300 
Changes:
Corrected the typo's as discussed in the meeting
No relevant UI changes

chore: Fix typos present in the app

---

app/src/main/java/org/fossasia/susi/ai/data/GroupWiseSkillsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/SkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/IGroupWiseSkillsModel.kt
app/src/main/java/org/fossasia/susi/ai/data/contract/ISkillListingModel.kt
app/src/main/java/org/fossasia/susi/ai/dataclasses/SkillsListQuery.kt
app/src/main/java/org/fossasia/susi/ai/helper/Constant.kt
app/src/main/java/org/fossasia/susi/ai/rest/ClientBuilder.kt
app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsFragment.kt
app/src/main/java/org/fossasia/susi/ai/skills/groupwiseskills/GroupWiseSkillsPresenter.kt
app/src/main/java/org/fossasia/susi/ai/skills/skilllisting/SkillListingPresenter.kt
app/src/main/res/drawable/ic_arrow_downward_blue_24dp.xml
app/src/main/res/drawable/ic_arrow_upward_blue_24dp.xml
app/src/main/res/drawable/ic_format_list_bulleted_black_24dp.xml
app/src/main/res/menu/skills_activity_menu.xml
app/src/main/res/values/strings.xml

Fixes #1458
Changes:
* Made the basic setup ready
* Implemented filter functionalities
APK: 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3413805/app-fdroid-debug.apk.zip)

feat: Filter skills according to the user choice

---

app/src/main/java/org/fossasia/susi/ai/skills/SkillsActivity.kt

Fixes #2315
Changes: 
* Fixed the visibility

fix: Remove filter options from settings page

---

app/build.gradle

Fixes #2320
Changes:
Updated the version number for new release.

chore: Update version number
